//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"html/template"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"

	chain_selectors "github.com/smartcontractkit/chain-selectors"
)

const filename = "generated_chains.go"

type chain struct {
	ChainID  string
	Selector uint64
	Name     string
	Family   string
	VarName  string
}

var chainTemplate, _ = template.New("").Parse(`// Code generated by go generate please DO NOT EDIT
package chain_selectors

type Chain struct {
	Selector   uint64
	Name       string
	ChainID    string
	Family     string
	VarName    string
}

var (
{{ range . }}
	{{.VarName}} = Chain{ChainID: "{{ .ChainID }}", Selector: {{ .Selector }}, Family: "{{ .Family }}", Name: "{{ .Name }}"}{{ end }}
)

var ALL = []Chain{
{{ range . }}{{ .VarName }},
{{ end }}
}

`)

func main() {
	src, err := genChainsSourceCode()
	if err != nil {
		panic(err)
	}

	formatted, err := format.Source([]byte(src))
	if err != nil {
		panic(err)
	}

	existingContent, err := os.ReadFile(filename)
	if err != nil {
		panic(err)
	}

	if string(existingContent) == string(formatted) {
		fmt.Println("no changes detected")
		return
	}

	err = os.WriteFile(filename, formatted, 0644)
	if err != nil {
		panic(err)
	}
}

func genChainsSourceCode() (string, error) {
	var wr = new(bytes.Buffer)
	chains := make([]chain, 0)

	for chainSelector, chainDetails := range chain_selectors.ChainSelectorToChainDetails() {
		chains = append(chains, chain{
			ChainID:  chainDetails.ChainID,
			Selector: chainSelector,
			Name:     chainDetails.Name,
			Family:   chainDetails.Family,
			VarName:  toVarName(chainDetails.Name, chainSelector),
		})
	}

	for chainSelector, chainDetails := range chain_selectors.TestChainSelectorToChainDetails() {
		chains = append(chains, chain{
			ChainID:  chainDetails.ChainID,
			Selector: chainSelector,
			Name:     chainDetails.Name,
			Family:   chainDetails.Family,
			VarName:  toVarName(chainDetails.Name, chainSelector),
		})
	}

	sort.Slice(chains, func(i, j int) bool { return chains[i].VarName < chains[j].VarName })
	if err := chainTemplate.ExecuteTemplate(wr, "", chains); err != nil {
		return "", err
	}
	return wr.String(), nil
}

func toVarName(name string, chainSel uint64) string {
	const unnamed = "TEST"
	x := strings.ReplaceAll(name, "-", "_")
	x = strings.ToUpper(x)
	if len(x) > 0 && unicode.IsDigit(rune(x[0])) {
		x = unnamed + "_" + x
	}
	if len(x) == 0 {
		x = unnamed + "_" + strconv.FormatUint(chainSel, 10)
	}
	return x
}
