//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
	"text/template"
	"unicode"

	"github.com/smartcontractkit/chain-selectors/internal/gotmpl"
)

const filename = "generated_chains_evm.go"

type chain struct {
	EvmChainID uint64
	Selector   uint64
	Name       string
	VarName    string
}

var chainTemplate, _ = template.New("").Parse(`// Code generated by go generate please DO NOT EDIT
package chain_selectors

type Chain struct {
	EvmChainID uint64
	Selector   uint64
	Name       string
	VarName    string
}

var (
{{ range . }}
	{{.VarName}} = Chain{EvmChainID: {{ .EvmChainID }}, Selector: {{ .Selector }}, Name: "{{ .Name }}"}{{ end }}
)

var ALL = []Chain{
{{ range . }}{{ .VarName }},
{{ end }}
}

`)

func main() {
	src, err := gotmpl.Run(chainTemplate, &goNameEncoder{})
	if err != nil {
		panic(err)
	}

	formatted, err := format.Source([]byte(src))
	if err != nil {
		panic(err)
	}

	existingContent, err := os.ReadFile(filename)
	if err != nil {
		panic(err)
	}

	if string(existingContent) == string(formatted) {
		fmt.Println("evm: no changes detected")
		return
	}
	fmt.Println("evm: updating generations")

	err = os.WriteFile(filename, formatted, 0644)
	if err != nil {
		panic(err)
	}
}

type goNameEncoder struct{}

func (*goNameEncoder) VarName(name string, chainSel uint64) string {
	const unnamed = "TEST"
	x := strings.ReplaceAll(name, "-", "_")
	x = strings.ToUpper(x)
	if len(x) > 0 && unicode.IsDigit(rune(x[0])) {
		x = unnamed + "_" + x
	}
	if len(x) == 0 {
		x = unnamed + "_" + strconv.FormatUint(chainSel, 10)
	}
	return x
}
