// Code generated by go generate please DO NOT EDIT
package chain_selectors

type AptosChain struct {
	ChainID   uint64
	Selector  uint64
	Name      string
	VarName   string
	IsMainnet bool
}

var (
	APTOS_LOCALNET = AptosChain{ChainID: 4, Selector: 4457093679053095497, Name: "aptos-localnet", IsMainnet: false}
	APTOS_MAINNET  = AptosChain{ChainID: 1, Selector: 4741433654826277614, Name: "aptos-mainnet", IsMainnet: true}
	APTOS_TESTNET  = AptosChain{ChainID: 2, Selector: 743186221051783445, Name: "aptos-testnet", IsMainnet: false}
)

var AptosALL = []AptosChain{
	APTOS_LOCALNET,
	APTOS_MAINNET,
	APTOS_TESTNET,
}
