// Code generated by go generate please DO NOT EDIT
package chain_selectors

type TonChain struct {
	ChainID  int32
	Selector uint64
	Name     string
	VarName  string
}

var (
	TON_MAINNET = TonChain{ChainID: -239, Selector: 16448340667252469081, Name: "ton-mainnet"}
	TON_TESTNET = TonChain{ChainID: -3, Selector: 1399300952838017768, Name: "ton-testnet"}
)

var TonALL = []TonChain{
	TON_MAINNET,
	TON_TESTNET,
}
