// Code generated by go generate please DO NOT EDIT
package chain_selectors

type SolanaChain struct {
	ChainID  string
	Selector uint64
	Name     string
	VarName  string
}

var (
	SOLANA_DEVNET                                     = SolanaChain{ChainID: "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG", Selector: 16423721717087811551, Name: "solana-devnet"}
	SOLANA_MAINNET                                    = SolanaChain{ChainID: "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d", Selector: 124615329519749607, Name: "solana-mainnet"}
	SOLANA_TESTNET                                    = SolanaChain{ChainID: "4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY", Selector: 6302590918974934319, Name: "solana-testnet"}
	TEST_7ZWZQPZ5RQNJE9ZGHWEZ6KVUFBGQYXHH6T7DJHDU6IXY = SolanaChain{ChainID: "7ZWZqpZ5RQNjE9zGHwEz6KvuFbGQyxhh6t7DJHDu6iXy", Selector: 12463857294658392847, Name: "7ZWZqpZ5RQNjE9zGHwEz6KvuFbGQyxhh6t7DJHDu6iXy"}
	TEST_BXE7UWXVA4ZSTANZ8QZ1VSWYM3GUMBPOQOKAHWXMKWZW = SolanaChain{ChainID: "BxE7UwXVa4zStanz8Qz1vsWyM3gUMbpoQokAhWxmKWZw", Selector: 9837465928374658293, Name: "BxE7UwXVa4zStanz8Qz1vsWyM3gUMbpoQokAhWxmKWZw"}
	TEST_GH92RUKQZC8SDP3YPGGZQKKC8NC9DRXRPZEBE2YPDPNU = SolanaChain{ChainID: "Gh92RUkqZC8sdP3yPGGzqkKc8nC9DRXrPZeBE2YPdPnu", Selector: 16574839267584930184, Name: "Gh92RUkqZC8sdP3yPGGzqkKc8nC9DRXrPZeBE2YPdPnu"}
)

var SolanaALL = []SolanaChain{
	SOLANA_DEVNET,
	SOLANA_MAINNET,
	SOLANA_TESTNET,
	TEST_7ZWZQPZ5RQNJE9ZGHWEZ6KVUFBGQYXHH6T7DJHDU6IXY,
	TEST_BXE7UWXVA4ZSTANZ8QZ1VSWYM3GUMBPOQOKAHWXMKWZW,
	TEST_GH92RUKQZC8SDP3YPGGZQKKC8NC9DRXRPZEBE2YPDPNU,
}
