// Code generated by go generate please DO NOT EDIT
package chain_selectors

type TonChain struct {
	ChainID   int32
	Selector  uint64
	Name      string
	VarName   string
	IsMainnet bool
}

var (
	TON_LOCALNET = TonChain{ChainID: -217, Selector: 13879075125137744094, Name: "ton-localnet", IsMainnet: false}
	TON_MAINNET  = TonChain{ChainID: -239, Selector: 16448340667252469081, Name: "ton-mainnet", IsMainnet: true}
	TON_TESTNET  = TonChain{ChainID: -3, Selector: 1399300952838017768, Name: "ton-testnet", IsMainnet: false}
)

var TonALL = []TonChain{
	TON_LOCALNET,
	TON_MAINNET,
	TON_TESTNET,
}
