// Code generated by go generate please DO NOT EDIT
package chain_selectors

type SuiChain struct {
	ChainID  uint64
	Selector uint64
	Name     string
	VarName  string
}

var (
	SUI_LOCALNET = SuiChain{ChainID: 4, Selector: 0, Name: "sui-localnet"}
	SUI_MAINNET  = SuiChain{ChainID: 1, Selector: 0, Name: "sui-mainnet"}
	SUI_TESTNET  = SuiChain{ChainID: 2, Selector: 0, Name: "sui-testnet"}
)

var SuiALL = []SuiChain{
	SUI_LOCALNET,
	SUI_MAINNET,
	SUI_TESTNET,
}
