// Code generated by go generate please DO NOT EDIT
package chain_selectors

type AvalancheChain struct {
	ChainID  string
	Selector uint64
	Name     string
	VarName  string
}

var (
	AVALANCHE_TESTNET_PCHAIN = AvalancheChain{ChainID: "P_CHAIN", Selector: 14538442734262914677, Name: "avalanche-testnet-pchain"}
)

var AvalancheALL = []AvalancheChain{
	AVALANCHE_TESTNET_PCHAIN,
}
