// Code generated by go generate please DO NOT EDIT
package chain_selectors

type Chain struct {
	EVMChainID uint64
	Selector   uint64
	Name       string
	ChainID    string
	Family     string
	VarName    string
}

var (
	AREON_MAINNET                                  = Chain{ChainID: "463", EVMChainID: 463, Selector: 1939936305787790600, Family: "evm", Name: "areon-mainnet"}
	AREON_TESTNET                                  = Chain{ChainID: "462", EVMChainID: 462, Selector: 7317911323415911000, Family: "evm", Name: "areon-testnet"}
	AVALANCHE_MAINNET                              = Chain{ChainID: "43114", EVMChainID: 43114, Selector: 6433500567565415381, Family: "evm", Name: "avalanche-mainnet"}
	AVALANCHE_SUBNET_DEXALOT_MAINNET               = Chain{ChainID: "432204", EVMChainID: 432204, Selector: 5463201557265485081, Family: "evm", Name: "avalanche-subnet-dexalot-mainnet"}
	AVALANCHE_SUBNET_DEXALOT_TESTNET               = Chain{ChainID: "432201", EVMChainID: 432201, Selector: 1458281248224512906, Family: "evm", Name: "avalanche-subnet-dexalot-testnet"}
	AVALANCHE_TESTNET_FUJI                         = Chain{ChainID: "43113", EVMChainID: 43113, Selector: 14767482510784806043, Family: "evm", Name: "avalanche-testnet-fuji"}
	AVALANCHE_TESTNET_NEXON                        = Chain{ChainID: "595581", EVMChainID: 595581, Selector: 7837562506228496256, Family: "evm", Name: "avalanche-testnet-nexon"}
	BERACHAIN_TESTNET_ARTIO                        = Chain{ChainID: "80085", EVMChainID: 80085, Selector: 12336603543561911511, Family: "evm", Name: "berachain-testnet-artio"}
	BERACHAIN_TESTNET_BARTIO                       = Chain{ChainID: "80084", EVMChainID: 80084, Selector: 8999465244383784164, Family: "evm", Name: "berachain-testnet-bartio"}
	BINANCE_SMART_CHAIN_MAINNET                    = Chain{ChainID: "56", EVMChainID: 56, Selector: 11344663589394136015, Family: "evm", Name: "binance_smart_chain-mainnet"}
	BINANCE_SMART_CHAIN_MAINNET_OPBNB_1            = Chain{ChainID: "204", EVMChainID: 204, Selector: 465944652040885897, Family: "evm", Name: "binance_smart_chain-mainnet-opbnb-1"}
	BINANCE_SMART_CHAIN_TESTNET                    = Chain{ChainID: "97", EVMChainID: 97, Selector: 13264668187771770619, Family: "evm", Name: "binance_smart_chain-testnet"}
	BINANCE_SMART_CHAIN_TESTNET_OPBNB_1            = Chain{ChainID: "5611", EVMChainID: 5611, Selector: 13274425992935471758, Family: "evm", Name: "binance_smart_chain-testnet-opbnb-1"}
	BITCICHAIN_MAINNET                             = Chain{ChainID: "1907", EVMChainID: 1907, Selector: 4874388048629246000, Family: "evm", Name: "bitcichain-mainnet"}
	BITCICHAIN_TESTNET                             = Chain{ChainID: "1908", EVMChainID: 1908, Selector: 4888058894222120000, Family: "evm", Name: "bitcichain-testnet"}
	BITCOIN_MAINNET_BITLAYER_1                     = Chain{ChainID: "200901", EVMChainID: 200901, Selector: 7937294810946806131, Family: "evm", Name: "bitcoin-mainnet-bitlayer-1"}
	BITCOIN_MAINNET_BOB_1                          = Chain{ChainID: "60808", EVMChainID: 60808, Selector: 3849287863852499584, Family: "evm", Name: "bitcoin-mainnet-bob-1"}
	BITCOIN_MAINNET_BOTANIX                        = Chain{ChainID: "3637", EVMChainID: 3637, Selector: 4560701533377838164, Family: "evm", Name: "bitcoin-mainnet-botanix"}
	BITCOIN_MAINNET_BSQUARED_1                     = Chain{ChainID: "223", EVMChainID: 223, Selector: 5406759801798337480, Family: "evm", Name: "bitcoin-mainnet-bsquared-1"}
	BITCOIN_MERLIN_MAINNET                         = Chain{ChainID: "4200", EVMChainID: 4200, Selector: 241851231317828981, Family: "evm", Name: "bitcoin-merlin-mainnet"}
	BITCOIN_TESTNET_BITLAYER_1                     = Chain{ChainID: "200810", EVMChainID: 200810, Selector: 3789623672476206327, Family: "evm", Name: "bitcoin-testnet-bitlayer-1"}
	BITCOIN_TESTNET_BOTANIX                        = Chain{ChainID: "3636", EVMChainID: 3636, Selector: 1467223411771711614, Family: "evm", Name: "bitcoin-testnet-botanix"}
	BITCOIN_TESTNET_BSQUARED_1                     = Chain{ChainID: "1123", EVMChainID: 1123, Selector: 1948510578179542068, Family: "evm", Name: "bitcoin-testnet-bsquared-1"}
	BITCOIN_TESTNET_MERLIN                         = Chain{ChainID: "686868", EVMChainID: 686868, Selector: 5269261765892944301, Family: "evm", Name: "bitcoin-testnet-merlin"}
	BITCOIN_TESTNET_ROOTSTOCK                      = Chain{ChainID: "31", EVMChainID: 31, Selector: 8953668971247136127, Family: "evm", Name: "bitcoin-testnet-rootstock"}
	BITCOIN_TESTNET_SEPOLIA_BOB_1                  = Chain{ChainID: "808813", EVMChainID: 808813, Selector: 5535534526963509396, Family: "evm", Name: "bitcoin-testnet-sepolia-bob-1"}
	BITTORRENT_CHAIN_MAINNET                       = Chain{ChainID: "199", EVMChainID: 199, Selector: 3776006016387883143, Family: "evm", Name: "bittorrent_chain-mainnet"}
	BITTORRENT_CHAIN_TESTNET                       = Chain{ChainID: "1029", EVMChainID: 1029, Selector: 4459371029167934217, Family: "evm", Name: "bittorrent_chain-testnet"}
	CELO_MAINNET                                   = Chain{ChainID: "42220", EVMChainID: 42220, Selector: 1346049177634351622, Family: "evm", Name: "celo-mainnet"}
	CELO_TESTNET_ALFAJORES                         = Chain{ChainID: "44787", EVMChainID: 44787, Selector: 3552045678561919002, Family: "evm", Name: "celo-testnet-alfajores"}
	COINEX_SMART_CHAIN_MAINNET                     = Chain{ChainID: "52", EVMChainID: 52, Selector: 1761333065194157300, Family: "evm", Name: "coinex_smart_chain-mainnet"}
	COINEX_SMART_CHAIN_TESTNET                     = Chain{ChainID: "53", EVMChainID: 53, Selector: 8955032871639343000, Family: "evm", Name: "coinex_smart_chain-testnet"}
	CRONOS_MAINNET                                 = Chain{ChainID: "25", EVMChainID: 25, Selector: 1456215246176062136, Family: "evm", Name: "cronos-mainnet"}
	CRONOS_TESTNET                                 = Chain{ChainID: "338", EVMChainID: 338, Selector: 2995292832068775165, Family: "evm", Name: "cronos-testnet"}
	CRONOS_TESTNET_ZKEVM_1                         = Chain{ChainID: "282", EVMChainID: 282, Selector: 3842103497652714138, Family: "evm", Name: "cronos-testnet-zkevm-1"}
	ETHEREUM_MAINNET                               = Chain{ChainID: "1", EVMChainID: 1, Selector: 5009297550715157269, Family: "evm", Name: "ethereum-mainnet"}
	ETHEREUM_MAINNET_ARBITRUM_1                    = Chain{ChainID: "42161", EVMChainID: 42161, Selector: 4949039107694359620, Family: "evm", Name: "ethereum-mainnet-arbitrum-1"}
	ETHEREUM_MAINNET_ARBITRUM_1_L3X_1              = Chain{ChainID: "12324", EVMChainID: 12324, Selector: 3162193654116181371, Family: "evm", Name: "ethereum-mainnet-arbitrum-1-l3x-1"}
	ETHEREUM_MAINNET_ARBITRUM_1_TREASURE_1         = Chain{ChainID: "978670", EVMChainID: 978670, Selector: 1010349088906777999, Family: "evm", Name: "ethereum-mainnet-arbitrum-1-treasure-1"}
	ETHEREUM_MAINNET_ASTAR_ZKEVM_1                 = Chain{ChainID: "3776", EVMChainID: 3776, Selector: 1540201334317828111, Family: "evm", Name: "ethereum-mainnet-astar-zkevm-1"}
	ETHEREUM_MAINNET_BASE_1                        = Chain{ChainID: "8453", EVMChainID: 8453, Selector: 15971525489660198786, Family: "evm", Name: "ethereum-mainnet-base-1"}
	ETHEREUM_MAINNET_BLAST_1                       = Chain{ChainID: "81457", EVMChainID: 81457, Selector: 4411394078118774322, Family: "evm", Name: "ethereum-mainnet-blast-1"}
	ETHEREUM_MAINNET_IMMUTABLE_ZKEVM_1             = Chain{ChainID: "13371", EVMChainID: 13371, Selector: 1237925231416731909, Family: "evm", Name: "ethereum-mainnet-immutable-zkevm-1"}
	ETHEREUM_MAINNET_KROMA_1                       = Chain{ChainID: "255", EVMChainID: 255, Selector: 3719320017875267166, Family: "evm", Name: "ethereum-mainnet-kroma-1"}
	ETHEREUM_MAINNET_LINEA_1                       = Chain{ChainID: "59144", EVMChainID: 59144, Selector: 4627098889531055414, Family: "evm", Name: "ethereum-mainnet-linea-1"}
	ETHEREUM_MAINNET_MANTLE_1                      = Chain{ChainID: "5000", EVMChainID: 5000, Selector: 1556008542357238666, Family: "evm", Name: "ethereum-mainnet-mantle-1"}
	ETHEREUM_MAINNET_METIS_1                       = Chain{ChainID: "1088", EVMChainID: 1088, Selector: 8805746078405598895, Family: "evm", Name: "ethereum-mainnet-metis-1"}
	ETHEREUM_MAINNET_MODE_1                        = Chain{ChainID: "34443", EVMChainID: 34443, Selector: 7264351850409363825, Family: "evm", Name: "ethereum-mainnet-mode-1"}
	ETHEREUM_MAINNET_OPTIMISM_1                    = Chain{ChainID: "10", EVMChainID: 10, Selector: 3734403246176062136, Family: "evm", Name: "ethereum-mainnet-optimism-1"}
	ETHEREUM_MAINNET_POLYGON_ZKEVM_1               = Chain{ChainID: "1101", EVMChainID: 1101, Selector: 4348158687435793198, Family: "evm", Name: "ethereum-mainnet-polygon-zkevm-1"}
	ETHEREUM_MAINNET_SCROLL_1                      = Chain{ChainID: "534352", EVMChainID: 534352, Selector: 13204309965629103672, Family: "evm", Name: "ethereum-mainnet-scroll-1"}
	ETHEREUM_MAINNET_TAIKO_1                       = Chain{ChainID: "16700", EVMChainID: 16700, Selector: 16468599424800719238, Family: "evm", Name: "ethereum-mainnet-taiko-1"}
	ETHEREUM_MAINNET_WORLDCHAIN_1                  = Chain{ChainID: "480", EVMChainID: 480, Selector: 2049429975587534727, Family: "evm", Name: "ethereum-mainnet-worldchain-1"}
	ETHEREUM_MAINNET_XLAYER_1                      = Chain{ChainID: "196", EVMChainID: 196, Selector: 3016212468291539606, Family: "evm", Name: "ethereum-mainnet-xlayer-1"}
	ETHEREUM_MAINNET_ZKSYNC_1                      = Chain{ChainID: "324", EVMChainID: 324, Selector: 1562403441176082196, Family: "evm", Name: "ethereum-mainnet-zksync-1"}
	ETHEREUM_TESTNET_GOERLI_ARBITRUM_1             = Chain{ChainID: "421613", EVMChainID: 421613, Selector: 6101244977088475029, Family: "evm", Name: "ethereum-testnet-goerli-arbitrum-1"}
	ETHEREUM_TESTNET_GOERLI_BASE_1                 = Chain{ChainID: "84531", EVMChainID: 84531, Selector: 5790810961207155433, Family: "evm", Name: "ethereum-testnet-goerli-base-1"}
	ETHEREUM_TESTNET_GOERLI_LINEA_1                = Chain{ChainID: "59140", EVMChainID: 59140, Selector: 1355246678561316402, Family: "evm", Name: "ethereum-testnet-goerli-linea-1"}
	ETHEREUM_TESTNET_GOERLI_MANTLE_1               = Chain{ChainID: "5001", EVMChainID: 5001, Selector: 4168263376276232250, Family: "evm", Name: "ethereum-testnet-goerli-mantle-1"}
	ETHEREUM_TESTNET_GOERLI_OPTIMISM_1             = Chain{ChainID: "420", EVMChainID: 420, Selector: 2664363617261496610, Family: "evm", Name: "ethereum-testnet-goerli-optimism-1"}
	ETHEREUM_TESTNET_GOERLI_POLYGON_ZKEVM_1        = Chain{ChainID: "1442", EVMChainID: 1442, Selector: 11059667695644972511, Family: "evm", Name: "ethereum-testnet-goerli-polygon-zkevm-1"}
	ETHEREUM_TESTNET_GOERLI_ZKSYNC_1               = Chain{ChainID: "280", EVMChainID: 280, Selector: 6802309497652714138, Family: "evm", Name: "ethereum-testnet-goerli-zksync-1"}
	ETHEREUM_TESTNET_HOLESKY                       = Chain{ChainID: "17000", EVMChainID: 17000, Selector: 7717148896336251131, Family: "evm", Name: "ethereum-testnet-holesky"}
	ETHEREUM_TESTNET_HOLESKY_FRAXTAL_1             = Chain{ChainID: "2522", EVMChainID: 2522, Selector: 8901520481741771655, Family: "evm", Name: "ethereum-testnet-holesky-fraxtal-1"}
	ETHEREUM_TESTNET_HOLESKY_MORPH_1               = Chain{ChainID: "2810", EVMChainID: 2810, Selector: 8304510386741731151, Family: "evm", Name: "ethereum-testnet-holesky-morph-1"}
	ETHEREUM_TESTNET_HOLESKY_TAIKO_1               = Chain{ChainID: "167009", EVMChainID: 167009, Selector: 7248756420937879088, Family: "evm", Name: "ethereum-testnet-holesky-taiko-1"}
	ETHEREUM_TESTNET_SEPOLIA                       = Chain{ChainID: "11155111", EVMChainID: 11155111, Selector: 16015286601757825753, Family: "evm", Name: "ethereum-testnet-sepolia"}
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1            = Chain{ChainID: "421614", EVMChainID: 421614, Selector: 3478487238524512106, Family: "evm", Name: "ethereum-testnet-sepolia-arbitrum-1"}
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1_L3X_1      = Chain{ChainID: "12325", EVMChainID: 12325, Selector: 3486622437121596122, Family: "evm", Name: "ethereum-testnet-sepolia-arbitrum-1-l3x-1"}
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1_TREASURE_1 = Chain{ChainID: "978657", EVMChainID: 978657, Selector: 10443705513486043421, Family: "evm", Name: "ethereum-testnet-sepolia-arbitrum-1-treasure-1"}
	ETHEREUM_TESTNET_SEPOLIA_BASE_1                = Chain{ChainID: "84532", EVMChainID: 84532, Selector: 10344971235874465080, Family: "evm", Name: "ethereum-testnet-sepolia-base-1"}
	ETHEREUM_TESTNET_SEPOLIA_BLAST_1               = Chain{ChainID: "168587773", EVMChainID: 168587773, Selector: 2027362563942762617, Family: "evm", Name: "ethereum-testnet-sepolia-blast-1"}
	ETHEREUM_TESTNET_SEPOLIA_CORN_1                = Chain{ChainID: "21000000", EVMChainID: 21000000, Selector: 1467427327723633929, Family: "evm", Name: "ethereum-testnet-sepolia-corn-1"}
	ETHEREUM_TESTNET_SEPOLIA_IMMUTABLE_ZKEVM_1     = Chain{ChainID: "13473", EVMChainID: 13473, Selector: 4526165231216331901, Family: "evm", Name: "ethereum-testnet-sepolia-immutable-zkevm-1"}
	ETHEREUM_TESTNET_SEPOLIA_KROMA_1               = Chain{ChainID: "2358", EVMChainID: 2358, Selector: 5990477251245693094, Family: "evm", Name: "ethereum-testnet-sepolia-kroma-1"}
	ETHEREUM_TESTNET_SEPOLIA_LENS_1                = Chain{ChainID: "37111", EVMChainID: 37111, Selector: 6827576821754315911, Family: "evm", Name: "ethereum-testnet-sepolia-lens-1"}
	ETHEREUM_TESTNET_SEPOLIA_LINEA_1               = Chain{ChainID: "59141", EVMChainID: 59141, Selector: 5719461335882077547, Family: "evm", Name: "ethereum-testnet-sepolia-linea-1"}
	ETHEREUM_TESTNET_SEPOLIA_LISK_1                = Chain{ChainID: "4202", EVMChainID: 4202, Selector: 5298399861320400553, Family: "evm", Name: "ethereum-testnet-sepolia-lisk-1"}
	ETHEREUM_TESTNET_SEPOLIA_MANTLE_1              = Chain{ChainID: "5003", EVMChainID: 5003, Selector: 8236463271206331221, Family: "evm", Name: "ethereum-testnet-sepolia-mantle-1"}
	ETHEREUM_TESTNET_SEPOLIA_METIS_1               = Chain{ChainID: "59902", EVMChainID: 59902, Selector: 3777822886988675105, Family: "evm", Name: "ethereum-testnet-sepolia-metis-1"}
	ETHEREUM_TESTNET_SEPOLIA_MODE_1                = Chain{ChainID: "919", EVMChainID: 919, Selector: 829525985033418733, Family: "evm", Name: "ethereum-testnet-sepolia-mode-1"}
	ETHEREUM_TESTNET_SEPOLIA_OPTIMISM_1            = Chain{ChainID: "11155420", EVMChainID: 11155420, Selector: 5224473277236331295, Family: "evm", Name: "ethereum-testnet-sepolia-optimism-1"}
	ETHEREUM_TESTNET_SEPOLIA_POLYGON_VALIDIUM_1    = Chain{ChainID: "717160", EVMChainID: 717160, Selector: 4418231248214522936, Family: "evm", Name: "ethereum-testnet-sepolia-polygon-validium-1"}
	ETHEREUM_TESTNET_SEPOLIA_POLYGON_ZKEVM_1       = Chain{ChainID: "2442", EVMChainID: 2442, Selector: 1654667687261492630, Family: "evm", Name: "ethereum-testnet-sepolia-polygon-zkevm-1"}
	ETHEREUM_TESTNET_SEPOLIA_SCROLL_1              = Chain{ChainID: "534351", EVMChainID: 534351, Selector: 2279865765895943307, Family: "evm", Name: "ethereum-testnet-sepolia-scroll-1"}
	ETHEREUM_TESTNET_SEPOLIA_SONEIUM_1             = Chain{ChainID: "1946", EVMChainID: 1946, Selector: 686603546605904534, Family: "evm", Name: "ethereum-testnet-sepolia-soneium-1"}
	ETHEREUM_TESTNET_SEPOLIA_UNICHAIN_1            = Chain{ChainID: "1301", EVMChainID: 1301, Selector: 14135854469784514356, Family: "evm", Name: "ethereum-testnet-sepolia-unichain-1"}
	ETHEREUM_TESTNET_SEPOLIA_WORLDCHAIN_1          = Chain{ChainID: "4801", EVMChainID: 4801, Selector: 5299555114858065850, Family: "evm", Name: "ethereum-testnet-sepolia-worldchain-1"}
	ETHEREUM_TESTNET_SEPOLIA_XLAYER_1              = Chain{ChainID: "195", EVMChainID: 195, Selector: 2066098519157881736, Family: "evm", Name: "ethereum-testnet-sepolia-xlayer-1"}
	ETHEREUM_TESTNET_SEPOLIA_ZIRCUIT_1             = Chain{ChainID: "48899", EVMChainID: 48899, Selector: 4562743618362911021, Family: "evm", Name: "ethereum-testnet-sepolia-zircuit-1"}
	ETHEREUM_TESTNET_SEPOLIA_ZKSYNC_1              = Chain{ChainID: "300", EVMChainID: 300, Selector: 6898391096552792247, Family: "evm", Name: "ethereum-testnet-sepolia-zksync-1"}
	FANTOM_MAINNET                                 = Chain{ChainID: "250", EVMChainID: 250, Selector: 3768048213127883732, Family: "evm", Name: "fantom-mainnet"}
	FANTOM_TESTNET                                 = Chain{ChainID: "4002", EVMChainID: 4002, Selector: 4905564228793744293, Family: "evm", Name: "fantom-testnet"}
	FILECOIN_MAINNET                               = Chain{ChainID: "314", EVMChainID: 314, Selector: 4561443241176882990, Family: "evm", Name: "filecoin-mainnet"}
	FILECOIN_TESTNET                               = Chain{ChainID: "31415926", EVMChainID: 31415926, Selector: 7060342227814389000, Family: "evm", Name: "filecoin-testnet"}
	FRAXTAL_MAINNET                                = Chain{ChainID: "252", EVMChainID: 252, Selector: 1462016016387883143, Family: "evm", Name: "fraxtal-mainnet"}
	GETH_DEVNET_2                                  = Chain{ChainID: "2337", EVMChainID: 2337, Selector: 12922642891491394802, Family: "evm", Name: "geth-devnet-2"}
	GETH_DEVNET_3                                  = Chain{ChainID: "3337", EVMChainID: 3337, Selector: 4793464827907405086, Family: "evm", Name: "geth-devnet-3"}
	GETH_TESTNET                                   = Chain{ChainID: "1337", EVMChainID: 1337, Selector: 3379446385462418246, Family: "evm", Name: "geth-testnet"}
	GNOSIS_CHAIN_MAINNET                           = Chain{ChainID: "100", EVMChainID: 100, Selector: 465200170687744372, Family: "evm", Name: "gnosis_chain-mainnet"}
	GNOSIS_CHAIN_TESTNET_CHIADO                    = Chain{ChainID: "10200", EVMChainID: 10200, Selector: 8871595565390010547, Family: "evm", Name: "gnosis_chain-testnet-chiado"}
	HEDERA_MAINNET                                 = Chain{ChainID: "295", EVMChainID: 295, Selector: 3229138320728879060, Family: "evm", Name: "hedera-mainnet"}
	HEDERA_TESTNET                                 = Chain{ChainID: "296", EVMChainID: 296, Selector: 222782988166878823, Family: "evm", Name: "hedera-testnet"}
	HYPERLIQUID_TESTNET                            = Chain{ChainID: "998", EVMChainID: 998, Selector: 4286062357653186312, Family: "evm", Name: "hyperliquid-testnet"}
	KAVA_MAINNET                                   = Chain{ChainID: "2222", EVMChainID: 2222, Selector: 7550000543357438061, Family: "evm", Name: "kava-mainnet"}
	KAVA_TESTNET                                   = Chain{ChainID: "2221", EVMChainID: 2221, Selector: 2110537777356199208, Family: "evm", Name: "kava-testnet"}
	KUSAMA_MAINNET_MOONRIVER                       = Chain{ChainID: "1285", EVMChainID: 1285, Selector: 1355020143337428062, Family: "evm", Name: "kusama-mainnet-moonriver"}
	NEAR_MAINNET                                   = Chain{ChainID: "397", EVMChainID: 397, Selector: 2039744413822257700, Family: "evm", Name: "near-mainnet"}
	NEAR_TESTNET                                   = Chain{ChainID: "398", EVMChainID: 398, Selector: 5061593697262339000, Family: "evm", Name: "near-testnet"}
	NEONLINK_MAINNET                               = Chain{ChainID: "259", EVMChainID: 259, Selector: 8239338020728974000, Family: "evm", Name: "neonlink-mainnet"}
	NEONLINK_TESTNET                               = Chain{ChainID: "9559", EVMChainID: 9559, Selector: 1113014352258747600, Family: "evm", Name: "neonlink-testnet"}
	PLUME_TESTNET                                  = Chain{ChainID: "161221135", EVMChainID: 161221135, Selector: 14684575664602284776, Family: "evm", Name: "plume-testnet"}
	POLKADOT_MAINNET_ASTAR                         = Chain{ChainID: "592", EVMChainID: 592, Selector: 6422105447186081193, Family: "evm", Name: "polkadot-mainnet-astar"}
	POLKADOT_MAINNET_CENTRIFUGE                    = Chain{ChainID: "2031", EVMChainID: 2031, Selector: 8175830712062617656, Family: "evm", Name: "polkadot-mainnet-centrifuge"}
	POLKADOT_MAINNET_DARWINIA                      = Chain{ChainID: "46", EVMChainID: 46, Selector: 8866418665544333000, Family: "evm", Name: "polkadot-mainnet-darwinia"}
	POLKADOT_MAINNET_MOONBEAM                      = Chain{ChainID: "1284", EVMChainID: 1284, Selector: 1252863800116739621, Family: "evm", Name: "polkadot-mainnet-moonbeam"}
	POLKADOT_TESTNET_ASTAR_SHIBUYA                 = Chain{ChainID: "81", EVMChainID: 81, Selector: 6955638871347136141, Family: "evm", Name: "polkadot-testnet-astar-shibuya"}
	POLKADOT_TESTNET_CENTRIFUGE_ALTAIR             = Chain{ChainID: "2088", EVMChainID: 2088, Selector: 2333097300889804761, Family: "evm", Name: "polkadot-testnet-centrifuge-altair"}
	POLKADOT_TESTNET_DARWINIA_PANGORO              = Chain{ChainID: "45", EVMChainID: 45, Selector: 4340886533089894000, Family: "evm", Name: "polkadot-testnet-darwinia-pangoro"}
	POLKADOT_TESTNET_MOONBEAM_MOONBASE             = Chain{ChainID: "1287", EVMChainID: 1287, Selector: 5361632739113536121, Family: "evm", Name: "polkadot-testnet-moonbeam-moonbase"}
	POLYGON_MAINNET                                = Chain{ChainID: "137", EVMChainID: 137, Selector: 4051577828743386545, Family: "evm", Name: "polygon-mainnet"}
	POLYGON_TESTNET_AMOY                           = Chain{ChainID: "80002", EVMChainID: 80002, Selector: 16281711391670634445, Family: "evm", Name: "polygon-testnet-amoy"}
	POLYGON_TESTNET_MUMBAI                         = Chain{ChainID: "80001", EVMChainID: 80001, Selector: 12532609583862916517, Family: "evm", Name: "polygon-testnet-mumbai"}
	PRIVATE_TESTNET_MICA                           = Chain{ChainID: "424242", EVMChainID: 424242, Selector: 4489326297382772450, Family: "evm", Name: "private-testnet-mica"}
	PRIVATE_TESTNET_OPALA                          = Chain{ChainID: "45439", EVMChainID: 45439, Selector: 8446413392851542429, Family: "evm", Name: "private-testnet-opala"}
	RONIN_MAINNET                                  = Chain{ChainID: "2020", EVMChainID: 2020, Selector: 6916147374840168594, Family: "evm", Name: "ronin-mainnet"}
	RONIN_TESTNET_SAIGON                           = Chain{ChainID: "2021", EVMChainID: 2021, Selector: 13116810400804392105, Family: "evm", Name: "ronin-testnet-saigon"}
	SEI_MAINNET                                    = Chain{ChainID: "1329", EVMChainID: 1329, Selector: 9027416829622342829, Family: "evm", Name: "sei-mainnet"}
	SEI_TESTNET_ATLANTIC                           = Chain{ChainID: "1328", EVMChainID: 1328, Selector: 1216300075444106652, Family: "evm", Name: "sei-testnet-atlantic"}
	SOLANA_DEVNET                                  = Chain{ChainID: "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG", EVMChainID: 0, Selector: 16423721717087811551, Family: "solana", Name: "solana-devnet"}
	SOLANA_MAINNET                                 = Chain{ChainID: "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d", EVMChainID: 0, Selector: 124615329519749607, Family: "solana", Name: "solana-mainnet"}
	SOLANA_TESTNET                                 = Chain{ChainID: "4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY", EVMChainID: 0, Selector: 6302590918974934319, Family: "solana", Name: "solana-testnet"}
	SONIC_TESTNET                                  = Chain{ChainID: "64165", EVMChainID: 64165, Selector: 3676871237479449268, Family: "evm", Name: "sonic-testnet"}
	STORY_TESTNET                                  = Chain{ChainID: "1513", EVMChainID: 1513, Selector: 4237030917318060427, Family: "evm", Name: "story-testnet"}
	TELOS_EVM_MAINNET                              = Chain{ChainID: "40", EVMChainID: 40, Selector: 1477345371608778000, Family: "evm", Name: "telos-evm-mainnet"}
	TELOS_EVM_TESTNET                              = Chain{ChainID: "41", EVMChainID: 41, Selector: 729797994450396300, Family: "evm", Name: "telos-evm-testnet"}
	TEST_10089241509396411113                      = Chain{ChainID: "90000051", EVMChainID: 90000051, Selector: 10089241509396411113, Family: "evm", Name: ""}
	TEST_10106333385848939617                      = Chain{ChainID: "90000089", EVMChainID: 90000089, Selector: 10106333385848939617, Family: "evm", Name: ""}
	TEST_10199579733509604193                      = Chain{ChainID: "90000029", EVMChainID: 90000029, Selector: 10199579733509604193, Family: "evm", Name: ""}
	TEST_10497629267361915835                      = Chain{ChainID: "90000087", EVMChainID: 90000087, Selector: 10497629267361915835, Family: "evm", Name: ""}
	TEST_10537986502862404866                      = Chain{ChainID: "90000088", EVMChainID: 90000088, Selector: 10537986502862404866, Family: "evm", Name: ""}
	TEST_10547673735879567911                      = Chain{ChainID: "90000038", EVMChainID: 90000038, Selector: 10547673735879567911, Family: "evm", Name: ""}
	TEST_11335955773964346155                      = Chain{ChainID: "90000070", EVMChainID: 90000070, Selector: 11335955773964346155, Family: "evm", Name: ""}
	TEST_11754399446572002459                      = Chain{ChainID: "90000030", EVMChainID: 90000030, Selector: 11754399446572002459, Family: "evm", Name: ""}
	TEST_11787463284727550157                      = Chain{ChainID: "1000", EVMChainID: 1000, Selector: 11787463284727550157, Family: "evm", Name: ""}
	TEST_11985232338641871056                      = Chain{ChainID: "90000017", EVMChainID: 90000017, Selector: 11985232338641871056, Family: "evm", Name: ""}
	TEST_12027427861168955422                      = Chain{ChainID: "90000061", EVMChainID: 90000061, Selector: 12027427861168955422, Family: "evm", Name: ""}
	TEST_12226902941055802385                      = Chain{ChainID: "90000037", EVMChainID: 90000037, Selector: 12226902941055802385, Family: "evm", Name: ""}
	TEST_12470167056735102403                      = Chain{ChainID: "90000067", EVMChainID: 90000067, Selector: 12470167056735102403, Family: "evm", Name: ""}
	TEST_12499149790922928210                      = Chain{ChainID: "90000091", EVMChainID: 90000091, Selector: 12499149790922928210, Family: "evm", Name: ""}
	TEST_12513826466599144030                      = Chain{ChainID: "90000063", EVMChainID: 90000063, Selector: 12513826466599144030, Family: "evm", Name: ""}
	TEST_1273605685587320666                       = Chain{ChainID: "90000019", EVMChainID: 90000019, Selector: 1273605685587320666, Family: "evm", Name: ""}
	TEST_12965905455277595820                      = Chain{ChainID: "90000042", EVMChainID: 90000042, Selector: 12965905455277595820, Family: "evm", Name: ""}
	TEST_13087962012083037329                      = Chain{ChainID: "90000016", EVMChainID: 90000016, Selector: 13087962012083037329, Family: "evm", Name: ""}
	TEST_13443138560923813712                      = Chain{ChainID: "90000097", EVMChainID: 90000097, Selector: 13443138560923813712, Family: "evm", Name: ""}
	TEST_13648736134397881410                      = Chain{ChainID: "90000021", EVMChainID: 90000021, Selector: 13648736134397881410, Family: "evm", Name: ""}
	TEST_13781595843667691007                      = Chain{ChainID: "90000059", EVMChainID: 90000059, Selector: 13781595843667691007, Family: "evm", Name: ""}
	TEST_13819071330241498802                      = Chain{ChainID: "90000081", EVMChainID: 90000081, Selector: 13819071330241498802, Family: "evm", Name: ""}
	TEST_13936493323944617843                      = Chain{ChainID: "90000056", EVMChainID: 90000056, Selector: 13936493323944617843, Family: "evm", Name: ""}
	TEST_13973515790491921010                      = Chain{ChainID: "90000036", EVMChainID: 90000036, Selector: 13973515790491921010, Family: "evm", Name: ""}
	TEST_14506622911400094011                      = Chain{ChainID: "90000074", EVMChainID: 90000074, Selector: 14506622911400094011, Family: "evm", Name: ""}
	TEST_1488785539820432596                       = Chain{ChainID: "90000066", EVMChainID: 90000066, Selector: 1488785539820432596, Family: "evm", Name: ""}
	TEST_14943531413383612703                      = Chain{ChainID: "90000046", EVMChainID: 90000046, Selector: 14943531413383612703, Family: "evm", Name: ""}
	TEST_15168140751097121912                      = Chain{ChainID: "90000077", EVMChainID: 90000077, Selector: 15168140751097121912, Family: "evm", Name: ""}
	TEST_15210860601736105873                      = Chain{ChainID: "90000071", EVMChainID: 90000071, Selector: 15210860601736105873, Family: "evm", Name: ""}
	TEST_15447447865219782832                      = Chain{ChainID: "90000072", EVMChainID: 90000072, Selector: 15447447865219782832, Family: "evm", Name: ""}
	TEST_15733873364998401606                      = Chain{ChainID: "90000028", EVMChainID: 90000028, Selector: 15733873364998401606, Family: "evm", Name: ""}
	TEST_15767478222558315144                      = Chain{ChainID: "90000054", EVMChainID: 90000054, Selector: 15767478222558315144, Family: "evm", Name: ""}
	TEST_15804983202763665802                      = Chain{ChainID: "90000031", EVMChainID: 90000031, Selector: 15804983202763665802, Family: "evm", Name: ""}
	TEST_15896959195233368219                      = Chain{ChainID: "90000080", EVMChainID: 90000080, Selector: 15896959195233368219, Family: "evm", Name: ""}
	TEST_15945074456050759193                      = Chain{ChainID: "90000095", EVMChainID: 90000095, Selector: 15945074456050759193, Family: "evm", Name: ""}
	TEST_15998314635132476942                      = Chain{ChainID: "90000034", EVMChainID: 90000034, Selector: 15998314635132476942, Family: "evm", Name: ""}
	TEST_16449698933146693970                      = Chain{ChainID: "90000024", EVMChainID: 90000024, Selector: 16449698933146693970, Family: "evm", Name: ""}
	TEST_16591966440843528322                      = Chain{ChainID: "90000049", EVMChainID: 90000049, Selector: 16591966440843528322, Family: "evm", Name: ""}
	TEST_16702426279731183946                      = Chain{ChainID: "90000023", EVMChainID: 90000023, Selector: 16702426279731183946, Family: "evm", Name: ""}
	TEST_17251043223284625647                      = Chain{ChainID: "90000045", EVMChainID: 90000045, Selector: 17251043223284625647, Family: "evm", Name: ""}
	TEST_17514102371649734225                      = Chain{ChainID: "90000093", EVMChainID: 90000093, Selector: 17514102371649734225, Family: "evm", Name: ""}
	TEST_17580537314894454709                      = Chain{ChainID: "90000096", EVMChainID: 90000096, Selector: 17580537314894454709, Family: "evm", Name: ""}
	TEST_176199025415897437                        = Chain{ChainID: "90000044", EVMChainID: 90000044, Selector: 176199025415897437, Family: "evm", Name: ""}
	TEST_17759418850483131633                      = Chain{ChainID: "90000065", EVMChainID: 90000065, Selector: 17759418850483131633, Family: "evm", Name: ""}
	TEST_17810359353458878177                      = Chain{ChainID: "90000020", EVMChainID: 90000020, Selector: 17810359353458878177, Family: "evm", Name: ""}
	TEST_18316006852148771137                      = Chain{ChainID: "90000075", EVMChainID: 90000075, Selector: 18316006852148771137, Family: "evm", Name: ""}
	TEST_1974710175227680991                       = Chain{ChainID: "90000079", EVMChainID: 90000079, Selector: 1974710175227680991, Family: "evm", Name: ""}
	TEST_2509173735760116798                       = Chain{ChainID: "90000090", EVMChainID: 90000090, Selector: 2509173735760116798, Family: "evm", Name: ""}
	TEST_2783890746839497525                       = Chain{ChainID: "90000048", EVMChainID: 90000048, Selector: 2783890746839497525, Family: "evm", Name: ""}
	TEST_2953028829530698683                       = Chain{ChainID: "90000039", EVMChainID: 90000039, Selector: 2953028829530698683, Family: "evm", Name: ""}
	TEST_328334718812072308                        = Chain{ChainID: "90000011", EVMChainID: 90000011, Selector: 328334718812072308, Family: "evm", Name: ""}
	TEST_3330151784927722907                       = Chain{ChainID: "90000083", EVMChainID: 90000083, Selector: 3330151784927722907, Family: "evm", Name: ""}
	TEST_3574539439524578558                       = Chain{ChainID: "90000013", EVMChainID: 90000013, Selector: 3574539439524578558, Family: "evm", Name: ""}
	TEST_3632230855428784129                       = Chain{ChainID: "90000082", EVMChainID: 90000082, Selector: 3632230855428784129, Family: "evm", Name: ""}
	TEST_3740583887329090549                       = Chain{ChainID: "90000040", EVMChainID: 90000040, Selector: 3740583887329090549, Family: "evm", Name: ""}
	TEST_4066443121807923198                       = Chain{ChainID: "90000008", EVMChainID: 90000008, Selector: 4066443121807923198, Family: "evm", Name: ""}
	TEST_4174149892778961910                       = Chain{ChainID: "90000086", EVMChainID: 90000086, Selector: 4174149892778961910, Family: "evm", Name: ""}
	TEST_4543928599863227519                       = Chain{ChainID: "90000014", EVMChainID: 90000014, Selector: 4543928599863227519, Family: "evm", Name: ""}
	TEST_4716670523656754658                       = Chain{ChainID: "90000041", EVMChainID: 90000041, Selector: 4716670523656754658, Family: "evm", Name: ""}
	TEST_5548718428018410741                       = Chain{ChainID: "90000002", EVMChainID: 90000002, Selector: 5548718428018410741, Family: "evm", Name: ""}
	TEST_5614341928911841614                       = Chain{ChainID: "90000025", EVMChainID: 90000025, Selector: 5614341928911841614, Family: "evm", Name: ""}
	TEST_5721565186521185178                       = Chain{ChainID: "90000004", EVMChainID: 90000004, Selector: 5721565186521185178, Family: "evm", Name: ""}
	TEST_6059917085984771915                       = Chain{ChainID: "90000068", EVMChainID: 90000068, Selector: 6059917085984771915, Family: "evm", Name: ""}
	TEST_6443235356619661032                       = Chain{ChainID: "90000015", EVMChainID: 90000015, Selector: 6443235356619661032, Family: "evm", Name: ""}
	TEST_6448403805635971860                       = Chain{ChainID: "90000043", EVMChainID: 90000043, Selector: 6448403805635971860, Family: "evm", Name: ""}
	TEST_665284410079532457                        = Chain{ChainID: "90000092", EVMChainID: 90000092, Selector: 665284410079532457, Family: "evm", Name: ""}
	TEST_6676710761873615962                       = Chain{ChainID: "90000035", EVMChainID: 90000035, Selector: 6676710761873615962, Family: "evm", Name: ""}
	TEST_6690738652320128159                       = Chain{ChainID: "90000062", EVMChainID: 90000062, Selector: 6690738652320128159, Family: "evm", Name: ""}
	TEST_6742472197519042017                       = Chain{ChainID: "90000022", EVMChainID: 90000022, Selector: 6742472197519042017, Family: "evm", Name: ""}
	TEST_6747736380229414777                       = Chain{ChainID: "90000009", EVMChainID: 90000009, Selector: 6747736380229414777, Family: "evm", Name: ""}
	TEST_6751512843227450641                       = Chain{ChainID: "90000060", EVMChainID: 90000060, Selector: 6751512843227450641, Family: "evm", Name: ""}
	TEST_6875898693582952601                       = Chain{ChainID: "90000100", EVMChainID: 90000100, Selector: 6875898693582952601, Family: "evm", Name: ""}
	TEST_7005880874640146484                       = Chain{ChainID: "90000033", EVMChainID: 90000033, Selector: 7005880874640146484, Family: "evm", Name: ""}
	TEST_7032045258883126022                       = Chain{ChainID: "90000058", EVMChainID: 90000058, Selector: 7032045258883126022, Family: "evm", Name: ""}
	TEST_7353384334508842175                       = Chain{ChainID: "90000085", EVMChainID: 90000085, Selector: 7353384334508842175, Family: "evm", Name: ""}
	TEST_7404045285477377670                       = Chain{ChainID: "90000073", EVMChainID: 90000073, Selector: 7404045285477377670, Family: "evm", Name: ""}
	TEST_7431973150957944526                       = Chain{ChainID: "90000099", EVMChainID: 90000099, Selector: 7431973150957944526, Family: "evm", Name: ""}
	TEST_7585715102059681757                       = Chain{ChainID: "90000052", EVMChainID: 90000052, Selector: 7585715102059681757, Family: "evm", Name: ""}
	TEST_7715160997071429212                       = Chain{ChainID: "90000012", EVMChainID: 90000012, Selector: 7715160997071429212, Family: "evm", Name: ""}
	TEST_7777066535355430289                       = Chain{ChainID: "90000018", EVMChainID: 90000018, Selector: 7777066535355430289, Family: "evm", Name: ""}
	TEST_781901677223027175                        = Chain{ChainID: "76578", EVMChainID: 76578, Selector: 781901677223027175, Family: "evm", Name: ""}
	TEST_7823363553221722351                       = Chain{ChainID: "90000064", EVMChainID: 90000064, Selector: 7823363553221722351, Family: "evm", Name: ""}
	TEST_789068866484373046                        = Chain{ChainID: "90000003", EVMChainID: 90000003, Selector: 789068866484373046, Family: "evm", Name: ""}
	TEST_7961714422080771198                       = Chain{ChainID: "90000076", EVMChainID: 90000076, Selector: 7961714422080771198, Family: "evm", Name: ""}
	TEST_8015762103567576333                       = Chain{ChainID: "90000047", EVMChainID: 90000047, Selector: 8015762103567576333, Family: "evm", Name: ""}
	TEST_8211981504472319767                       = Chain{ChainID: "90000094", EVMChainID: 90000094, Selector: 8211981504472319767, Family: "evm", Name: ""}
	TEST_8354317460459584308                       = Chain{ChainID: "90000078", EVMChainID: 90000078, Selector: 8354317460459584308, Family: "evm", Name: ""}
	TEST_8412806778050735057                       = Chain{ChainID: "90000007", EVMChainID: 90000007, Selector: 8412806778050735057, Family: "evm", Name: ""}
	TEST_8694984074292254623                       = Chain{ChainID: "90000010", EVMChainID: 90000010, Selector: 8694984074292254623, Family: "evm", Name: ""}
	TEST_8698844633699288298                       = Chain{ChainID: "90000069", EVMChainID: 90000069, Selector: 8698844633699288298, Family: "evm", Name: ""}
	TEST_8794884152664322911                       = Chain{ChainID: "90000032", EVMChainID: 90000032, Selector: 8794884152664322911, Family: "evm", Name: ""}
	TEST_8966794841936584464                       = Chain{ChainID: "90000006", EVMChainID: 90000006, Selector: 8966794841936584464, Family: "evm", Name: ""}
	TEST_909606746561742123                        = Chain{ChainID: "90000001", EVMChainID: 90000001, Selector: 909606746561742123, Family: "evm", Name: ""}
	TEST_9156614022853705708                       = Chain{ChainID: "90000050", EVMChainID: 90000050, Selector: 9156614022853705708, Family: "evm", Name: ""}
	TEST_9248511054298050610                       = Chain{ChainID: "90000027", EVMChainID: 90000027, Selector: 9248511054298050610, Family: "evm", Name: ""}
	TEST_9264503539336248559                       = Chain{ChainID: "90000057", EVMChainID: 90000057, Selector: 9264503539336248559, Family: "evm", Name: ""}
	TEST_928756709184343973                        = Chain{ChainID: "90000055", EVMChainID: 90000055, Selector: 928756709184343973, Family: "evm", Name: ""}
	TEST_9574369650680012313                       = Chain{ChainID: "90000053", EVMChainID: 90000053, Selector: 9574369650680012313, Family: "evm", Name: ""}
	TEST_964127714438319834                        = Chain{ChainID: "90000005", EVMChainID: 90000005, Selector: 964127714438319834, Family: "evm", Name: ""}
	TEST_9675086780529785020                       = Chain{ChainID: "90000098", EVMChainID: 90000098, Selector: 9675086780529785020, Family: "evm", Name: ""}
	TEST_973671184102733124                        = Chain{ChainID: "90000084", EVMChainID: 90000084, Selector: 973671184102733124, Family: "evm", Name: ""}
	TEST_9932483170498916221                       = Chain{ChainID: "90000026", EVMChainID: 90000026, Selector: 9932483170498916221, Family: "evm", Name: ""}
	VELAS_MAINNET                                  = Chain{ChainID: "106", EVMChainID: 106, Selector: 374210358663784372, Family: "evm", Name: "velas-mainnet"}
	VELAS_TESTNET                                  = Chain{ChainID: "111", EVMChainID: 111, Selector: 572210378683744374, Family: "evm", Name: "velas-testnet"}
	WEMIX_MAINNET                                  = Chain{ChainID: "1111", EVMChainID: 1111, Selector: 5142893604156789321, Family: "evm", Name: "wemix-mainnet"}
	WEMIX_TESTNET                                  = Chain{ChainID: "1112", EVMChainID: 1112, Selector: 9284632837123596123, Family: "evm", Name: "wemix-testnet"}
	ZIRCUIT_MAINNET                                = Chain{ChainID: "48900", EVMChainID: 48900, Selector: 17198166215261833993, Family: "evm", Name: "zircuit-mainnet"}
	ZKLINK_NOVA_MAINNET                            = Chain{ChainID: "810180", EVMChainID: 810180, Selector: 4350319965322101699, Family: "evm", Name: "zklink_nova-mainnet"}
	ZKLINK_NOVA_TESTNET                            = Chain{ChainID: "810181", EVMChainID: 810181, Selector: 5837261596322416298, Family: "evm", Name: "zklink_nova-testnet"}
)

var ALL = []Chain{
	AREON_MAINNET,
	AREON_TESTNET,
	AVALANCHE_MAINNET,
	AVALANCHE_SUBNET_DEXALOT_MAINNET,
	AVALANCHE_SUBNET_DEXALOT_TESTNET,
	AVALANCHE_TESTNET_FUJI,
	AVALANCHE_TESTNET_NEXON,
	BERACHAIN_TESTNET_ARTIO,
	BERACHAIN_TESTNET_BARTIO,
	BINANCE_SMART_CHAIN_MAINNET,
	BINANCE_SMART_CHAIN_MAINNET_OPBNB_1,
	BINANCE_SMART_CHAIN_TESTNET,
	BINANCE_SMART_CHAIN_TESTNET_OPBNB_1,
	BITCICHAIN_MAINNET,
	BITCICHAIN_TESTNET,
	BITCOIN_MAINNET_BITLAYER_1,
	BITCOIN_MAINNET_BOB_1,
	BITCOIN_MAINNET_BOTANIX,
	BITCOIN_MAINNET_BSQUARED_1,
	BITCOIN_MERLIN_MAINNET,
	BITCOIN_TESTNET_BITLAYER_1,
	BITCOIN_TESTNET_BOTANIX,
	BITCOIN_TESTNET_BSQUARED_1,
	BITCOIN_TESTNET_MERLIN,
	BITCOIN_TESTNET_ROOTSTOCK,
	BITCOIN_TESTNET_SEPOLIA_BOB_1,
	BITTORRENT_CHAIN_MAINNET,
	BITTORRENT_CHAIN_TESTNET,
	CELO_MAINNET,
	CELO_TESTNET_ALFAJORES,
	COINEX_SMART_CHAIN_MAINNET,
	COINEX_SMART_CHAIN_TESTNET,
	CRONOS_MAINNET,
	CRONOS_TESTNET,
	CRONOS_TESTNET_ZKEVM_1,
	ETHEREUM_MAINNET,
	ETHEREUM_MAINNET_ARBITRUM_1,
	ETHEREUM_MAINNET_ARBITRUM_1_L3X_1,
	ETHEREUM_MAINNET_ARBITRUM_1_TREASURE_1,
	ETHEREUM_MAINNET_ASTAR_ZKEVM_1,
	ETHEREUM_MAINNET_BASE_1,
	ETHEREUM_MAINNET_BLAST_1,
	ETHEREUM_MAINNET_IMMUTABLE_ZKEVM_1,
	ETHEREUM_MAINNET_KROMA_1,
	ETHEREUM_MAINNET_LINEA_1,
	ETHEREUM_MAINNET_MANTLE_1,
	ETHEREUM_MAINNET_METIS_1,
	ETHEREUM_MAINNET_MODE_1,
	ETHEREUM_MAINNET_OPTIMISM_1,
	ETHEREUM_MAINNET_POLYGON_ZKEVM_1,
	ETHEREUM_MAINNET_SCROLL_1,
	ETHEREUM_MAINNET_TAIKO_1,
	ETHEREUM_MAINNET_WORLDCHAIN_1,
	ETHEREUM_MAINNET_XLAYER_1,
	ETHEREUM_MAINNET_ZKSYNC_1,
	ETHEREUM_TESTNET_GOERLI_ARBITRUM_1,
	ETHEREUM_TESTNET_GOERLI_BASE_1,
	ETHEREUM_TESTNET_GOERLI_LINEA_1,
	ETHEREUM_TESTNET_GOERLI_MANTLE_1,
	ETHEREUM_TESTNET_GOERLI_OPTIMISM_1,
	ETHEREUM_TESTNET_GOERLI_POLYGON_ZKEVM_1,
	ETHEREUM_TESTNET_GOERLI_ZKSYNC_1,
	ETHEREUM_TESTNET_HOLESKY,
	ETHEREUM_TESTNET_HOLESKY_FRAXTAL_1,
	ETHEREUM_TESTNET_HOLESKY_MORPH_1,
	ETHEREUM_TESTNET_HOLESKY_TAIKO_1,
	ETHEREUM_TESTNET_SEPOLIA,
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1,
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1_L3X_1,
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1_TREASURE_1,
	ETHEREUM_TESTNET_SEPOLIA_BASE_1,
	ETHEREUM_TESTNET_SEPOLIA_BLAST_1,
	ETHEREUM_TESTNET_SEPOLIA_CORN_1,
	ETHEREUM_TESTNET_SEPOLIA_IMMUTABLE_ZKEVM_1,
	ETHEREUM_TESTNET_SEPOLIA_KROMA_1,
	ETHEREUM_TESTNET_SEPOLIA_LENS_1,
	ETHEREUM_TESTNET_SEPOLIA_LINEA_1,
	ETHEREUM_TESTNET_SEPOLIA_LISK_1,
	ETHEREUM_TESTNET_SEPOLIA_MANTLE_1,
	ETHEREUM_TESTNET_SEPOLIA_METIS_1,
	ETHEREUM_TESTNET_SEPOLIA_MODE_1,
	ETHEREUM_TESTNET_SEPOLIA_OPTIMISM_1,
	ETHEREUM_TESTNET_SEPOLIA_POLYGON_VALIDIUM_1,
	ETHEREUM_TESTNET_SEPOLIA_POLYGON_ZKEVM_1,
	ETHEREUM_TESTNET_SEPOLIA_SCROLL_1,
	ETHEREUM_TESTNET_SEPOLIA_SONEIUM_1,
	ETHEREUM_TESTNET_SEPOLIA_UNICHAIN_1,
	ETHEREUM_TESTNET_SEPOLIA_WORLDCHAIN_1,
	ETHEREUM_TESTNET_SEPOLIA_XLAYER_1,
	ETHEREUM_TESTNET_SEPOLIA_ZIRCUIT_1,
	ETHEREUM_TESTNET_SEPOLIA_ZKSYNC_1,
	FANTOM_MAINNET,
	FANTOM_TESTNET,
	FILECOIN_MAINNET,
	FILECOIN_TESTNET,
	FRAXTAL_MAINNET,
	GETH_DEVNET_2,
	GETH_DEVNET_3,
	GETH_TESTNET,
	GNOSIS_CHAIN_MAINNET,
	GNOSIS_CHAIN_TESTNET_CHIADO,
	HEDERA_MAINNET,
	HEDERA_TESTNET,
	HYPERLIQUID_TESTNET,
	KAVA_MAINNET,
	KAVA_TESTNET,
	KUSAMA_MAINNET_MOONRIVER,
	NEAR_MAINNET,
	NEAR_TESTNET,
	NEONLINK_MAINNET,
	NEONLINK_TESTNET,
	PLUME_TESTNET,
	POLKADOT_MAINNET_ASTAR,
	POLKADOT_MAINNET_CENTRIFUGE,
	POLKADOT_MAINNET_DARWINIA,
	POLKADOT_MAINNET_MOONBEAM,
	POLKADOT_TESTNET_ASTAR_SHIBUYA,
	POLKADOT_TESTNET_CENTRIFUGE_ALTAIR,
	POLKADOT_TESTNET_DARWINIA_PANGORO,
	POLKADOT_TESTNET_MOONBEAM_MOONBASE,
	POLYGON_MAINNET,
	POLYGON_TESTNET_AMOY,
	POLYGON_TESTNET_MUMBAI,
	PRIVATE_TESTNET_MICA,
	PRIVATE_TESTNET_OPALA,
	RONIN_MAINNET,
	RONIN_TESTNET_SAIGON,
	SEI_MAINNET,
	SEI_TESTNET_ATLANTIC,
	SOLANA_DEVNET,
	SOLANA_MAINNET,
	SOLANA_TESTNET,
	SONIC_TESTNET,
	STORY_TESTNET,
	TELOS_EVM_MAINNET,
	TELOS_EVM_TESTNET,
	TEST_10089241509396411113,
	TEST_10106333385848939617,
	TEST_10199579733509604193,
	TEST_10497629267361915835,
	TEST_10537986502862404866,
	TEST_10547673735879567911,
	TEST_11335955773964346155,
	TEST_11754399446572002459,
	TEST_11787463284727550157,
	TEST_11985232338641871056,
	TEST_12027427861168955422,
	TEST_12226902941055802385,
	TEST_12470167056735102403,
	TEST_12499149790922928210,
	TEST_12513826466599144030,
	TEST_1273605685587320666,
	TEST_12965905455277595820,
	TEST_13087962012083037329,
	TEST_13443138560923813712,
	TEST_13648736134397881410,
	TEST_13781595843667691007,
	TEST_13819071330241498802,
	TEST_13936493323944617843,
	TEST_13973515790491921010,
	TEST_14506622911400094011,
	TEST_1488785539820432596,
	TEST_14943531413383612703,
	TEST_15168140751097121912,
	TEST_15210860601736105873,
	TEST_15447447865219782832,
	TEST_15733873364998401606,
	TEST_15767478222558315144,
	TEST_15804983202763665802,
	TEST_15896959195233368219,
	TEST_15945074456050759193,
	TEST_15998314635132476942,
	TEST_16449698933146693970,
	TEST_16591966440843528322,
	TEST_16702426279731183946,
	TEST_17251043223284625647,
	TEST_17514102371649734225,
	TEST_17580537314894454709,
	TEST_176199025415897437,
	TEST_17759418850483131633,
	TEST_17810359353458878177,
	TEST_18316006852148771137,
	TEST_1974710175227680991,
	TEST_2509173735760116798,
	TEST_2783890746839497525,
	TEST_2953028829530698683,
	TEST_328334718812072308,
	TEST_3330151784927722907,
	TEST_3574539439524578558,
	TEST_3632230855428784129,
	TEST_3740583887329090549,
	TEST_4066443121807923198,
	TEST_4174149892778961910,
	TEST_4543928599863227519,
	TEST_4716670523656754658,
	TEST_5548718428018410741,
	TEST_5614341928911841614,
	TEST_5721565186521185178,
	TEST_6059917085984771915,
	TEST_6443235356619661032,
	TEST_6448403805635971860,
	TEST_665284410079532457,
	TEST_6676710761873615962,
	TEST_6690738652320128159,
	TEST_6742472197519042017,
	TEST_6747736380229414777,
	TEST_6751512843227450641,
	TEST_6875898693582952601,
	TEST_7005880874640146484,
	TEST_7032045258883126022,
	TEST_7353384334508842175,
	TEST_7404045285477377670,
	TEST_7431973150957944526,
	TEST_7585715102059681757,
	TEST_7715160997071429212,
	TEST_7777066535355430289,
	TEST_781901677223027175,
	TEST_7823363553221722351,
	TEST_789068866484373046,
	TEST_7961714422080771198,
	TEST_8015762103567576333,
	TEST_8211981504472319767,
	TEST_8354317460459584308,
	TEST_8412806778050735057,
	TEST_8694984074292254623,
	TEST_8698844633699288298,
	TEST_8794884152664322911,
	TEST_8966794841936584464,
	TEST_909606746561742123,
	TEST_9156614022853705708,
	TEST_9248511054298050610,
	TEST_9264503539336248559,
	TEST_928756709184343973,
	TEST_9574369650680012313,
	TEST_964127714438319834,
	TEST_9675086780529785020,
	TEST_973671184102733124,
	TEST_9932483170498916221,
	VELAS_MAINNET,
	VELAS_TESTNET,
	WEMIX_MAINNET,
	WEMIX_TESTNET,
	ZIRCUIT_MAINNET,
	ZKLINK_NOVA_MAINNET,
	ZKLINK_NOVA_TESTNET,
}
