// Code generated by go generate please DO NOT EDIT
package chain_selectors

type SuiChain struct {
	ChainID   uint64
	Selector  uint64
	Name      string
	VarName   string
	IsMainnet bool
}

var (
	SUI_LOCALNET = SuiChain{ChainID: 4, Selector: 18395503381733958356, Name: "sui-localnet", IsMainnet: false}
	SUI_MAINNET  = SuiChain{ChainID: 1, Selector: 17529533435026248318, Name: "sui-mainnet", IsMainnet: true}
	SUI_TESTNET  = SuiChain{ChainID: 2, Selector: 9762610643973837292, Name: "sui-testnet", IsMainnet: false}
)

var SuiALL = []SuiChain{
	SUI_LOCALNET,
	SUI_MAINNET,
	SUI_TESTNET,
}
