// Code generated by go generate please DO NOT EDIT
package chain_selectors

type BeaconChain struct {
	ChainID  uint64
	Selector uint64
	Name     string
	VarName  string
}

var (
	ETHEREUM_BEACON_MAINNET = BeaconChain{ChainID: 1, Selector: 2007918196257561144, Name: "ethereum-beacon-mainnet"}
)

var BeaconALL = []BeaconChain{
	ETHEREUM_BEACON_MAINNET,
}
