// Code generated by go generate please DO NOT EDIT
package chain_selectors

type StarknetChain struct {
	ChainID  string
	Selector uint64
	Name     string
	VarName  string
}

var (
	ETHEREUM_MAINNET_STARKNET_1         = StarknetChain{ChainID: "SN_MAIN", Selector: 511843109281680063, Name: "ethereum-mainnet-starknet-1"}
	ETHEREUM_TESTNET_SEPOLIA_STARKNET_1 = StarknetChain{ChainID: "SN_SEPOLIA", Selector: 4115550741429562104, Name: "ethereum-testnet-sepolia-starknet-1"}
)

var StarknetALL = []StarknetChain{
	ETHEREUM_MAINNET_STARKNET_1,
	ETHEREUM_TESTNET_SEPOLIA_STARKNET_1,
}
