// Code generated by go generate please DO NOT EDIT
package chain_selectors

type DogecoinChain struct {
	ChainID  string
	Selector uint64
	Name     string
	VarName  string
}

var (
	DOGECOIN_MAINNET = DogecoinChain{ChainID: "dogecoin_mainnet", Selector: 16302150171372387475, Name: "dogecoin-mainnet"}
)

var DogecoinALL = []DogecoinChain{
	DOGECOIN_MAINNET,
}
