// Code generated by go generate please DO NOT EDIT
package chain_selectors

type Chain struct {
	Selector uint64
	Name     string
	ChainID  string
	VarName  string
}

var (
	AREON_MAINNET                                  = Chain{ChainID: "463", Selector: 1939936305787790600, Name: "areon-mainnet"}
	AREON_TESTNET                                  = Chain{ChainID: "462", Selector: 7317911323415911000, Name: "areon-testnet"}
	AVALANCHE_MAINNET                              = Chain{ChainID: "43114", Selector: 6433500567565415381, Name: "avalanche-mainnet"}
	AVALANCHE_SUBNET_DEXALOT_MAINNET               = Chain{ChainID: "432204", Selector: 5463201557265485081, Name: "avalanche-subnet-dexalot-mainnet"}
	AVALANCHE_SUBNET_DEXALOT_TESTNET               = Chain{ChainID: "432201", Selector: 1458281248224512906, Name: "avalanche-subnet-dexalot-testnet"}
	AVALANCHE_TESTNET_FUJI                         = Chain{ChainID: "43113", Selector: 14767482510784806043, Name: "avalanche-testnet-fuji"}
	AVALANCHE_TESTNET_NEXON                        = Chain{ChainID: "595581", Selector: 7837562506228496256, Name: "avalanche-testnet-nexon"}
	BERACHAIN_TESTNET_ARTIO                        = Chain{ChainID: "80085", Selector: 12336603543561911511, Name: "berachain-testnet-artio"}
	BERACHAIN_TESTNET_BARTIO                       = Chain{ChainID: "80084", Selector: 8999465244383784164, Name: "berachain-testnet-bartio"}
	BINANCE_SMART_CHAIN_MAINNET                    = Chain{ChainID: "56", Selector: 11344663589394136015, Name: "binance_smart_chain-mainnet"}
	BINANCE_SMART_CHAIN_MAINNET_OPBNB_1            = Chain{ChainID: "204", Selector: 465944652040885897, Name: "binance_smart_chain-mainnet-opbnb-1"}
	BINANCE_SMART_CHAIN_TESTNET                    = Chain{ChainID: "97", Selector: 13264668187771770619, Name: "binance_smart_chain-testnet"}
	BINANCE_SMART_CHAIN_TESTNET_OPBNB_1            = Chain{ChainID: "5611", Selector: 13274425992935471758, Name: "binance_smart_chain-testnet-opbnb-1"}
	BITCICHAIN_MAINNET                             = Chain{ChainID: "1907", Selector: 4874388048629246000, Name: "bitcichain-mainnet"}
	BITCICHAIN_TESTNET                             = Chain{ChainID: "1908", Selector: 4888058894222120000, Name: "bitcichain-testnet"}
	BITCOIN_MAINNET_BITLAYER_1                     = Chain{ChainID: "200901", Selector: 7937294810946806131, Name: "bitcoin-mainnet-bitlayer-1"}
	BITCOIN_MAINNET_BOB_1                          = Chain{ChainID: "60808", Selector: 3849287863852499584, Name: "bitcoin-mainnet-bob-1"}
	BITCOIN_MAINNET_BOTANIX                        = Chain{ChainID: "3637", Selector: 4560701533377838164, Name: "bitcoin-mainnet-botanix"}
	BITCOIN_MAINNET_BSQUARED_1                     = Chain{ChainID: "223", Selector: 5406759801798337480, Name: "bitcoin-mainnet-bsquared-1"}
	BITCOIN_MERLIN_MAINNET                         = Chain{ChainID: "4200", Selector: 241851231317828981, Name: "bitcoin-merlin-mainnet"}
	BITCOIN_TESTNET_BITLAYER_1                     = Chain{ChainID: "200810", Selector: 3789623672476206327, Name: "bitcoin-testnet-bitlayer-1"}
	BITCOIN_TESTNET_BOTANIX                        = Chain{ChainID: "3636", Selector: 1467223411771711614, Name: "bitcoin-testnet-botanix"}
	BITCOIN_TESTNET_BSQUARED_1                     = Chain{ChainID: "1123", Selector: 1948510578179542068, Name: "bitcoin-testnet-bsquared-1"}
	BITCOIN_TESTNET_MERLIN                         = Chain{ChainID: "11155420", Selector: 5269261765892944301, Name: "bitcoin-testnet-merlin"}
	BITCOIN_TESTNET_ROOTSTOCK                      = Chain{ChainID: "31", Selector: 8953668971247136127, Name: "bitcoin-testnet-rootstock"}
	BITCOIN_TESTNET_SEPOLIA_BOB_1                  = Chain{ChainID: "808813", Selector: 5535534526963509396, Name: "bitcoin-testnet-sepolia-bob-1"}
	BITTORRENT_CHAIN_MAINNET                       = Chain{ChainID: "199", Selector: 3776006016387883143, Name: "bittorrent_chain-mainnet"}
	BITTORRENT_CHAIN_TESTNET                       = Chain{ChainID: "1029", Selector: 4459371029167934217, Name: "bittorrent_chain-testnet"}
	CELO_MAINNET                                   = Chain{ChainID: "42220", Selector: 1346049177634351622, Name: "celo-mainnet"}
	CELO_TESTNET_ALFAJORES                         = Chain{ChainID: "44787", Selector: 3552045678561919002, Name: "celo-testnet-alfajores"}
	COINEX_SMART_CHAIN_MAINNET                     = Chain{ChainID: "52", Selector: 1761333065194157300, Name: "coinex_smart_chain-mainnet"}
	COINEX_SMART_CHAIN_TESTNET                     = Chain{ChainID: "53", Selector: 8955032871639343000, Name: "coinex_smart_chain-testnet"}
	CRONOS_MAINNET                                 = Chain{ChainID: "25", Selector: 1456215246176062136, Name: "cronos-mainnet"}
	CRONOS_TESTNET                                 = Chain{ChainID: "338", Selector: 2995292832068775165, Name: "cronos-testnet"}
	CRONOS_TESTNET_ZKEVM_1                         = Chain{ChainID: "282", Selector: 3842103497652714138, Name: "cronos-testnet-zkevm-1"}
	ETHEREUM_MAINNET                               = Chain{ChainID: "1", Selector: 5009297550715157269, Name: "ethereum-mainnet"}
	ETHEREUM_MAINNET_ARBITRUM_1                    = Chain{ChainID: "42161", Selector: 4949039107694359620, Name: "ethereum-mainnet-arbitrum-1"}
	ETHEREUM_MAINNET_ARBITRUM_1_L3X_1              = Chain{ChainID: "12324", Selector: 3162193654116181371, Name: "ethereum-mainnet-arbitrum-1-l3x-1"}
	ETHEREUM_MAINNET_ARBITRUM_1_TREASURE_1         = Chain{ChainID: "978670", Selector: 1010349088906777999, Name: "ethereum-mainnet-arbitrum-1-treasure-1"}
	ETHEREUM_MAINNET_ASTAR_ZKEVM_1                 = Chain{ChainID: "3776", Selector: 1540201334317828111, Name: "ethereum-mainnet-astar-zkevm-1"}
	ETHEREUM_MAINNET_BASE_1                        = Chain{ChainID: "8453", Selector: 15971525489660198786, Name: "ethereum-mainnet-base-1"}
	ETHEREUM_MAINNET_BLAST_1                       = Chain{ChainID: "81457", Selector: 4411394078118774322, Name: "ethereum-mainnet-blast-1"}
	ETHEREUM_MAINNET_IMMUTABLE_ZKEVM_1             = Chain{ChainID: "13371", Selector: 1237925231416731909, Name: "ethereum-mainnet-immutable-zkevm-1"}
	ETHEREUM_MAINNET_KROMA_1                       = Chain{ChainID: "255", Selector: 3719320017875267166, Name: "ethereum-mainnet-kroma-1"}
	ETHEREUM_MAINNET_LINEA_1                       = Chain{ChainID: "59144", Selector: 4627098889531055414, Name: "ethereum-mainnet-linea-1"}
	ETHEREUM_MAINNET_MANTLE_1                      = Chain{ChainID: "5000", Selector: 1556008542357238666, Name: "ethereum-mainnet-mantle-1"}
	ETHEREUM_MAINNET_METIS_1                       = Chain{ChainID: "1088", Selector: 8805746078405598895, Name: "ethereum-mainnet-metis-1"}
	ETHEREUM_MAINNET_MODE_1                        = Chain{ChainID: "34443", Selector: 7264351850409363825, Name: "ethereum-mainnet-mode-1"}
	ETHEREUM_MAINNET_OPTIMISM_1                    = Chain{ChainID: "10", Selector: 3734403246176062136, Name: "ethereum-mainnet-optimism-1"}
	ETHEREUM_MAINNET_POLYGON_ZKEVM_1               = Chain{ChainID: "1101", Selector: 4348158687435793198, Name: "ethereum-mainnet-polygon-zkevm-1"}
	ETHEREUM_MAINNET_SCROLL_1                      = Chain{ChainID: "534352", Selector: 13204309965629103672, Name: "ethereum-mainnet-scroll-1"}
	ETHEREUM_MAINNET_TAIKO_1                       = Chain{ChainID: "16700", Selector: 16468599424800719238, Name: "ethereum-mainnet-taiko-1"}
	ETHEREUM_MAINNET_WORLDCHAIN_1                  = Chain{ChainID: "480", Selector: 2049429975587534727, Name: "ethereum-mainnet-worldchain-1"}
	ETHEREUM_MAINNET_XLAYER_1                      = Chain{ChainID: "196", Selector: 3016212468291539606, Name: "ethereum-mainnet-xlayer-1"}
	ETHEREUM_MAINNET_ZKSYNC_1                      = Chain{ChainID: "324", Selector: 1562403441176082196, Name: "ethereum-mainnet-zksync-1"}
	ETHEREUM_TESTNET_GOERLI_ARBITRUM_1             = Chain{ChainID: "421613", Selector: 6101244977088475029, Name: "ethereum-testnet-goerli-arbitrum-1"}
	ETHEREUM_TESTNET_GOERLI_BASE_1                 = Chain{ChainID: "84531", Selector: 5790810961207155433, Name: "ethereum-testnet-goerli-base-1"}
	ETHEREUM_TESTNET_GOERLI_LINEA_1                = Chain{ChainID: "59140", Selector: 1355246678561316402, Name: "ethereum-testnet-goerli-linea-1"}
	ETHEREUM_TESTNET_GOERLI_MANTLE_1               = Chain{ChainID: "5001", Selector: 4168263376276232250, Name: "ethereum-testnet-goerli-mantle-1"}
	ETHEREUM_TESTNET_GOERLI_OPTIMISM_1             = Chain{ChainID: "420", Selector: 2664363617261496610, Name: "ethereum-testnet-goerli-optimism-1"}
	ETHEREUM_TESTNET_GOERLI_POLYGON_ZKEVM_1        = Chain{ChainID: "1442", Selector: 11059667695644972511, Name: "ethereum-testnet-goerli-polygon-zkevm-1"}
	ETHEREUM_TESTNET_GOERLI_ZKSYNC_1               = Chain{ChainID: "280", Selector: 6802309497652714138, Name: "ethereum-testnet-goerli-zksync-1"}
	ETHEREUM_TESTNET_HOLESKY                       = Chain{ChainID: "17000", Selector: 7717148896336251131, Name: "ethereum-testnet-holesky"}
	ETHEREUM_TESTNET_HOLESKY_FRAXTAL_1             = Chain{ChainID: "2522", Selector: 8901520481741771655, Name: "ethereum-testnet-holesky-fraxtal-1"}
	ETHEREUM_TESTNET_HOLESKY_MORPH_1               = Chain{ChainID: "2810", Selector: 8304510386741731151, Name: "ethereum-testnet-holesky-morph-1"}
	ETHEREUM_TESTNET_HOLESKY_TAIKO_1               = Chain{ChainID: "167009", Selector: 7248756420937879088, Name: "ethereum-testnet-holesky-taiko-1"}
	ETHEREUM_TESTNET_SEPOLIA                       = Chain{ChainID: "11155111", Selector: 16015286601757825753, Name: "ethereum-testnet-sepolia"}
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1            = Chain{ChainID: "421614", Selector: 3478487238524512106, Name: "ethereum-testnet-sepolia-arbitrum-1"}
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1_L3X_1      = Chain{ChainID: "12325", Selector: 3486622437121596122, Name: "ethereum-testnet-sepolia-arbitrum-1-l3x-1"}
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1_TREASURE_1 = Chain{ChainID: "978657", Selector: 10443705513486043421, Name: "ethereum-testnet-sepolia-arbitrum-1-treasure-1"}
	ETHEREUM_TESTNET_SEPOLIA_BASE_1                = Chain{ChainID: "84532", Selector: 10344971235874465080, Name: "ethereum-testnet-sepolia-base-1"}
	ETHEREUM_TESTNET_SEPOLIA_BLAST_1               = Chain{ChainID: "168587773", Selector: 2027362563942762617, Name: "ethereum-testnet-sepolia-blast-1"}
	ETHEREUM_TESTNET_SEPOLIA_CORN_1                = Chain{ChainID: "21000000", Selector: 1467427327723633929, Name: "ethereum-testnet-sepolia-corn-1"}
	ETHEREUM_TESTNET_SEPOLIA_IMMUTABLE_ZKEVM_1     = Chain{ChainID: "13473", Selector: 4526165231216331901, Name: "ethereum-testnet-sepolia-immutable-zkevm-1"}
	ETHEREUM_TESTNET_SEPOLIA_KROMA_1               = Chain{ChainID: "2358", Selector: 5990477251245693094, Name: "ethereum-testnet-sepolia-kroma-1"}
	ETHEREUM_TESTNET_SEPOLIA_LENS_1                = Chain{ChainID: "37111", Selector: 6827576821754315911, Name: "ethereum-testnet-sepolia-lens-1"}
	ETHEREUM_TESTNET_SEPOLIA_LINEA_1               = Chain{ChainID: "59141", Selector: 5719461335882077547, Name: "ethereum-testnet-sepolia-linea-1"}
	ETHEREUM_TESTNET_SEPOLIA_LISK_1                = Chain{ChainID: "4202", Selector: 5298399861320400553, Name: "ethereum-testnet-sepolia-lisk-1"}
	ETHEREUM_TESTNET_SEPOLIA_MANTLE_1              = Chain{ChainID: "5003", Selector: 8236463271206331221, Name: "ethereum-testnet-sepolia-mantle-1"}
	ETHEREUM_TESTNET_SEPOLIA_METIS_1               = Chain{ChainID: "59902", Selector: 3777822886988675105, Name: "ethereum-testnet-sepolia-metis-1"}
	ETHEREUM_TESTNET_SEPOLIA_MODE_1                = Chain{ChainID: "919", Selector: 829525985033418733, Name: "ethereum-testnet-sepolia-mode-1"}
	ETHEREUM_TESTNET_SEPOLIA_OPTIMISM_1            = Chain{ChainID: "11155420", Selector: 5224473277236331295, Name: "ethereum-testnet-sepolia-optimism-1"}
	ETHEREUM_TESTNET_SEPOLIA_POLYGON_VALIDIUM_1    = Chain{ChainID: "717160", Selector: 4418231248214522936, Name: "ethereum-testnet-sepolia-polygon-validium-1"}
	ETHEREUM_TESTNET_SEPOLIA_POLYGON_ZKEVM_1       = Chain{ChainID: "2442", Selector: 1654667687261492630, Name: "ethereum-testnet-sepolia-polygon-zkevm-1"}
	ETHEREUM_TESTNET_SEPOLIA_SCROLL_1              = Chain{ChainID: "534351", Selector: 2279865765895943307, Name: "ethereum-testnet-sepolia-scroll-1"}
	ETHEREUM_TESTNET_SEPOLIA_SONEIUM_1             = Chain{ChainID: "1946", Selector: 686603546605904534, Name: "ethereum-testnet-sepolia-soneium-1"}
	ETHEREUM_TESTNET_SEPOLIA_UNICHAIN_1            = Chain{ChainID: "1301", Selector: 14135854469784514356, Name: "ethereum-testnet-sepolia-unichain-1"}
	ETHEREUM_TESTNET_SEPOLIA_WORLDCHAIN_1          = Chain{ChainID: "4801", Selector: 5299555114858065850, Name: "ethereum-testnet-sepolia-worldchain-1"}
	ETHEREUM_TESTNET_SEPOLIA_XLAYER_1              = Chain{ChainID: "195", Selector: 2066098519157881736, Name: "ethereum-testnet-sepolia-xlayer-1"}
	ETHEREUM_TESTNET_SEPOLIA_ZIRCUIT_1             = Chain{ChainID: "48899", Selector: 4562743618362911021, Name: "ethereum-testnet-sepolia-zircuit-1"}
	ETHEREUM_TESTNET_SEPOLIA_ZKSYNC_1              = Chain{ChainID: "300", Selector: 6898391096552792247, Name: "ethereum-testnet-sepolia-zksync-1"}
	FANTOM_MAINNET                                 = Chain{ChainID: "250", Selector: 3768048213127883732, Name: "fantom-mainnet"}
	FANTOM_TESTNET                                 = Chain{ChainID: "4002", Selector: 4905564228793744293, Name: "fantom-testnet"}
	FILECOIN_MAINNET                               = Chain{ChainID: "314", Selector: 4561443241176882990, Name: "filecoin-mainnet"}
	FILECOIN_TESTNET                               = Chain{ChainID: "31415926", Selector: 7060342227814389000, Name: "filecoin-testnet"}
	FRAXTAL_MAINNET                                = Chain{ChainID: "252", Selector: 1462016016387883143, Name: "fraxtal-mainnet"}
	GETH_DEVNET_2                                  = Chain{ChainID: "", Selector: 12922642891491394802, Name: "geth-devnet-2"}
	GETH_DEVNET_3                                  = Chain{ChainID: "", Selector: 4793464827907405086, Name: "geth-devnet-3"}
	GETH_TESTNET                                   = Chain{ChainID: "1337", Selector: 3379446385462418246, Name: "geth-testnet"}
	GNOSIS_CHAIN_MAINNET                           = Chain{ChainID: "100", Selector: 465200170687744372, Name: "gnosis_chain-mainnet"}
	GNOSIS_CHAIN_TESTNET_CHIADO                    = Chain{ChainID: "10200", Selector: 8871595565390010547, Name: "gnosis_chain-testnet-chiado"}
	HEDERA_MAINNET                                 = Chain{ChainID: "295", Selector: 3229138320728879060, Name: "hedera-mainnet"}
	HEDERA_TESTNET                                 = Chain{ChainID: "296", Selector: 222782988166878823, Name: "hedera-testnet"}
	HYPERLIQUID_TESTNET                            = Chain{ChainID: "998", Selector: 4286062357653186312, Name: "hyperliquid-testnet"}
	KAVA_MAINNET                                   = Chain{ChainID: "2222", Selector: 7550000543357438061, Name: "kava-mainnet"}
	KAVA_TESTNET                                   = Chain{ChainID: "2221", Selector: 2110537777356199208, Name: "kava-testnet"}
	KUSAMA_MAINNET_MOONRIVER                       = Chain{ChainID: "1285", Selector: 1355020143337428062, Name: "kusama-mainnet-moonriver"}
	NEAR_MAINNET                                   = Chain{ChainID: "397", Selector: 2039744413822257700, Name: "near-mainnet"}
	NEAR_TESTNET                                   = Chain{ChainID: "398", Selector: 5061593697262339000, Name: "near-testnet"}
	NEONLINK_MAINNET                               = Chain{ChainID: "259", Selector: 8239338020728974000, Name: "neonlink-mainnet"}
	NEONLINK_TESTNET                               = Chain{ChainID: "9559", Selector: 1113014352258747600, Name: "neonlink-testnet"}
	PLUME_TESTNET                                  = Chain{ChainID: "161221135", Selector: 10199579733509604193, Name: "plume-testnet"}
	PLUME_TESTNET                                  = Chain{ChainID: "161221135", Selector: 14684575664602284776, Name: "plume-testnet"}
	POLKADOT_MAINNET_ASTAR                         = Chain{ChainID: "592", Selector: 6422105447186081193, Name: "polkadot-mainnet-astar"}
	POLKADOT_MAINNET_CENTRIFUGE                    = Chain{ChainID: "2031", Selector: 8175830712062617656, Name: "polkadot-mainnet-centrifuge"}
	POLKADOT_MAINNET_DARWINIA                      = Chain{ChainID: "46", Selector: 8866418665544333000, Name: "polkadot-mainnet-darwinia"}
	POLKADOT_MAINNET_MOONBEAM                      = Chain{ChainID: "1284", Selector: 1252863800116739621, Name: "polkadot-mainnet-moonbeam"}
	POLKADOT_TESTNET_ASTAR_SHIBUYA                 = Chain{ChainID: "81", Selector: 6955638871347136141, Name: "polkadot-testnet-astar-shibuya"}
	POLKADOT_TESTNET_CENTRIFUGE_ALTAIR             = Chain{ChainID: "2088", Selector: 2333097300889804761, Name: "polkadot-testnet-centrifuge-altair"}
	POLKADOT_TESTNET_DARWINIA_PANGORO              = Chain{ChainID: "45", Selector: 4340886533089894000, Name: "polkadot-testnet-darwinia-pangoro"}
	POLKADOT_TESTNET_MOONBEAM_MOONBASE             = Chain{ChainID: "1287", Selector: 5361632739113536121, Name: "polkadot-testnet-moonbeam-moonbase"}
	POLYGON_MAINNET                                = Chain{ChainID: "137", Selector: 4051577828743386545, Name: "polygon-mainnet"}
	POLYGON_TESTNET_AMOY                           = Chain{ChainID: "80002", Selector: 16281711391670634445, Name: "polygon-testnet-amoy"}
	POLYGON_TESTNET_MUMBAI                         = Chain{ChainID: "80001", Selector: 12532609583862916517, Name: "polygon-testnet-mumbai"}
	PRIVATE_TESTNET_MICA                           = Chain{ChainID: "424242", Selector: 4489326297382772450, Name: "private-testnet-mica"}
	PRIVATE_TESTNET_OPALA                          = Chain{ChainID: "45439", Selector: 8446413392851542429, Name: "private-testnet-opala"}
	RONIN_MAINNET                                  = Chain{ChainID: "2020", Selector: 6916147374840168594, Name: "ronin-mainnet"}
	RONIN_TESTNET_SAIGON                           = Chain{ChainID: "2021", Selector: 13116810400804392105, Name: "ronin-testnet-saigon"}
	SEI_MAINNET                                    = Chain{ChainID: "1329", Selector: 9027416829622342829, Name: "sei-mainnet"}
	SEI_TESTNET_ATLANTIC                           = Chain{ChainID: "1328", Selector: 1216300075444106652, Name: "sei-testnet-atlantic"}
	SOLANA_DEVNET                                  = Chain{ChainID: "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG", Selector: 16423721717087811551, Name: "solana-devnet"}
	SOLANA_MAINNET                                 = Chain{ChainID: "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d", Selector: 124615329519749607, Name: "solana-mainnet"}
	SOLANA_TESTNET                                 = Chain{ChainID: "4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY", Selector: 6302590918974934319, Name: "solana-testnet"}
	SONIC_TESTNET                                  = Chain{ChainID: "64165", Selector: 3676871237479449268, Name: "sonic-testnet"}
	STORY_TESTNET                                  = Chain{ChainID: "1513", Selector: 4237030917318060427, Name: "story-testnet"}
	TELOS_EVM_MAINNET                              = Chain{ChainID: "40", Selector: 1477345371608778000, Name: "telos-evm-mainnet"}
	TELOS_EVM_TESTNET                              = Chain{ChainID: "41", Selector: 729797994450396300, Name: "telos-evm-testnet"}
	TEST_10089241509396411113                      = Chain{ChainID: "", Selector: 10089241509396411113, Name: ""}
	TEST_10106333385848939617                      = Chain{ChainID: "", Selector: 10106333385848939617, Name: ""}
	TEST_10497629267361915835                      = Chain{ChainID: "", Selector: 10497629267361915835, Name: ""}
	TEST_10537986502862404866                      = Chain{ChainID: "", Selector: 10537986502862404866, Name: ""}
	TEST_10547673735879567911                      = Chain{ChainID: "76578", Selector: 10547673735879567911, Name: ""}
	TEST_11335955773964346155                      = Chain{ChainID: "", Selector: 11335955773964346155, Name: ""}
	TEST_11754399446572002459                      = Chain{ChainID: "", Selector: 11754399446572002459, Name: ""}
	TEST_11787463284727550157                      = Chain{ChainID: "", Selector: 11787463284727550157, Name: ""}
	TEST_11985232338641871056                      = Chain{ChainID: "", Selector: 11985232338641871056, Name: ""}
	TEST_12027427861168955422                      = Chain{ChainID: "", Selector: 12027427861168955422, Name: ""}
	TEST_12226902941055802385                      = Chain{ChainID: "", Selector: 12226902941055802385, Name: ""}
	TEST_12470167056735102403                      = Chain{ChainID: "", Selector: 12470167056735102403, Name: ""}
	TEST_12499149790922928210                      = Chain{ChainID: "", Selector: 12499149790922928210, Name: ""}
	TEST_12513826466599144030                      = Chain{ChainID: "", Selector: 12513826466599144030, Name: ""}
	TEST_1273605685587320666                       = Chain{ChainID: "", Selector: 1273605685587320666, Name: ""}
	TEST_12965905455277595820                      = Chain{ChainID: "", Selector: 12965905455277595820, Name: ""}
	TEST_13087962012083037329                      = Chain{ChainID: "", Selector: 13087962012083037329, Name: ""}
	TEST_13443138560923813712                      = Chain{ChainID: "", Selector: 13443138560923813712, Name: ""}
	TEST_13648736134397881410                      = Chain{ChainID: "", Selector: 13648736134397881410, Name: ""}
	TEST_13781595843667691007                      = Chain{ChainID: "", Selector: 13781595843667691007, Name: ""}
	TEST_13819071330241498802                      = Chain{ChainID: "", Selector: 13819071330241498802, Name: ""}
	TEST_13936493323944617843                      = Chain{ChainID: "", Selector: 13936493323944617843, Name: ""}
	TEST_13973515790491921010                      = Chain{ChainID: "", Selector: 13973515790491921010, Name: ""}
	TEST_14506622911400094011                      = Chain{ChainID: "", Selector: 14506622911400094011, Name: ""}
	TEST_1488785539820432596                       = Chain{ChainID: "", Selector: 1488785539820432596, Name: ""}
	TEST_14943531413383612703                      = Chain{ChainID: "", Selector: 14943531413383612703, Name: ""}
	TEST_15168140751097121912                      = Chain{ChainID: "", Selector: 15168140751097121912, Name: ""}
	TEST_15210860601736105873                      = Chain{ChainID: "", Selector: 15210860601736105873, Name: ""}
	TEST_15447447865219782832                      = Chain{ChainID: "", Selector: 15447447865219782832, Name: ""}
	TEST_15733873364998401606                      = Chain{ChainID: "", Selector: 15733873364998401606, Name: ""}
	TEST_15767478222558315144                      = Chain{ChainID: "", Selector: 15767478222558315144, Name: ""}
	TEST_15804983202763665802                      = Chain{ChainID: "", Selector: 15804983202763665802, Name: ""}
	TEST_15896959195233368219                      = Chain{ChainID: "", Selector: 15896959195233368219, Name: ""}
	TEST_15945074456050759193                      = Chain{ChainID: "", Selector: 15945074456050759193, Name: ""}
	TEST_15998314635132476942                      = Chain{ChainID: "", Selector: 15998314635132476942, Name: ""}
	TEST_16449698933146693970                      = Chain{ChainID: "", Selector: 16449698933146693970, Name: ""}
	TEST_16591966440843528322                      = Chain{ChainID: "", Selector: 16591966440843528322, Name: ""}
	TEST_16702426279731183946                      = Chain{ChainID: "", Selector: 16702426279731183946, Name: ""}
	TEST_17198166215261833993                      = Chain{ChainID: "48900", Selector: 17198166215261833993, Name: ""}
	TEST_17251043223284625647                      = Chain{ChainID: "", Selector: 17251043223284625647, Name: ""}
	TEST_17514102371649734225                      = Chain{ChainID: "", Selector: 17514102371649734225, Name: ""}
	TEST_17580537314894454709                      = Chain{ChainID: "", Selector: 17580537314894454709, Name: ""}
	TEST_176199025415897437                        = Chain{ChainID: "", Selector: 176199025415897437, Name: ""}
	TEST_17759418850483131633                      = Chain{ChainID: "", Selector: 17759418850483131633, Name: ""}
	TEST_17810359353458878177                      = Chain{ChainID: "", Selector: 17810359353458878177, Name: ""}
	TEST_18316006852148771137                      = Chain{ChainID: "", Selector: 18316006852148771137, Name: ""}
	TEST_1974710175227680991                       = Chain{ChainID: "", Selector: 1974710175227680991, Name: ""}
	TEST_2509173735760116798                       = Chain{ChainID: "", Selector: 2509173735760116798, Name: ""}
	TEST_2783890746839497525                       = Chain{ChainID: "", Selector: 2783890746839497525, Name: ""}
	TEST_2953028829530698683                       = Chain{ChainID: "", Selector: 2953028829530698683, Name: ""}
	TEST_328334718812072308                        = Chain{ChainID: "", Selector: 328334718812072308, Name: ""}
	TEST_3330151784927722907                       = Chain{ChainID: "", Selector: 3330151784927722907, Name: ""}
	TEST_3574539439524578558                       = Chain{ChainID: "", Selector: 3574539439524578558, Name: ""}
	TEST_3632230855428784129                       = Chain{ChainID: "", Selector: 3632230855428784129, Name: ""}
	TEST_3740583887329090549                       = Chain{ChainID: "", Selector: 3740583887329090549, Name: ""}
	TEST_4066443121807923198                       = Chain{ChainID: "", Selector: 4066443121807923198, Name: ""}
	TEST_4174149892778961910                       = Chain{ChainID: "", Selector: 4174149892778961910, Name: ""}
	TEST_4543928599863227519                       = Chain{ChainID: "", Selector: 4543928599863227519, Name: ""}
	TEST_4716670523656754658                       = Chain{ChainID: "", Selector: 4716670523656754658, Name: ""}
	TEST_5548718428018410741                       = Chain{ChainID: "", Selector: 5548718428018410741, Name: ""}
	TEST_5614341928911841614                       = Chain{ChainID: "", Selector: 5614341928911841614, Name: ""}
	TEST_5721565186521185178                       = Chain{ChainID: "", Selector: 5721565186521185178, Name: ""}
	TEST_6059917085984771915                       = Chain{ChainID: "", Selector: 6059917085984771915, Name: ""}
	TEST_6443235356619661032                       = Chain{ChainID: "", Selector: 6443235356619661032, Name: ""}
	TEST_6448403805635971860                       = Chain{ChainID: "", Selector: 6448403805635971860, Name: ""}
	TEST_665284410079532457                        = Chain{ChainID: "", Selector: 665284410079532457, Name: ""}
	TEST_6676710761873615962                       = Chain{ChainID: "", Selector: 6676710761873615962, Name: ""}
	TEST_6690738652320128159                       = Chain{ChainID: "", Selector: 6690738652320128159, Name: ""}
	TEST_6742472197519042017                       = Chain{ChainID: "", Selector: 6742472197519042017, Name: ""}
	TEST_6747736380229414777                       = Chain{ChainID: "", Selector: 6747736380229414777, Name: ""}
	TEST_6751512843227450641                       = Chain{ChainID: "", Selector: 6751512843227450641, Name: ""}
	TEST_6875898693582952601                       = Chain{ChainID: "", Selector: 6875898693582952601, Name: ""}
	TEST_7005880874640146484                       = Chain{ChainID: "", Selector: 7005880874640146484, Name: ""}
	TEST_7032045258883126022                       = Chain{ChainID: "", Selector: 7032045258883126022, Name: ""}
	TEST_7353384334508842175                       = Chain{ChainID: "", Selector: 7353384334508842175, Name: ""}
	TEST_7404045285477377670                       = Chain{ChainID: "", Selector: 7404045285477377670, Name: ""}
	TEST_7431973150957944526                       = Chain{ChainID: "", Selector: 7431973150957944526, Name: ""}
	TEST_7585715102059681757                       = Chain{ChainID: "", Selector: 7585715102059681757, Name: ""}
	TEST_7715160997071429212                       = Chain{ChainID: "", Selector: 7715160997071429212, Name: ""}
	TEST_7777066535355430289                       = Chain{ChainID: "", Selector: 7777066535355430289, Name: ""}
	TEST_781901677223027175                        = Chain{ChainID: "", Selector: 781901677223027175, Name: ""}
	TEST_7823363553221722351                       = Chain{ChainID: "", Selector: 7823363553221722351, Name: ""}
	TEST_789068866484373046                        = Chain{ChainID: "", Selector: 789068866484373046, Name: ""}
	TEST_7961714422080771198                       = Chain{ChainID: "", Selector: 7961714422080771198, Name: ""}
	TEST_8015762103567576333                       = Chain{ChainID: "", Selector: 8015762103567576333, Name: ""}
	TEST_8211981504472319767                       = Chain{ChainID: "", Selector: 8211981504472319767, Name: ""}
	TEST_8354317460459584308                       = Chain{ChainID: "", Selector: 8354317460459584308, Name: ""}
	TEST_8412806778050735057                       = Chain{ChainID: "", Selector: 8412806778050735057, Name: ""}
	TEST_8694984074292254623                       = Chain{ChainID: "", Selector: 8694984074292254623, Name: ""}
	TEST_8698844633699288298                       = Chain{ChainID: "", Selector: 8698844633699288298, Name: ""}
	TEST_8794884152664322911                       = Chain{ChainID: "", Selector: 8794884152664322911, Name: ""}
	TEST_8966794841936584464                       = Chain{ChainID: "", Selector: 8966794841936584464, Name: ""}
	TEST_909606746561742123                        = Chain{ChainID: "", Selector: 909606746561742123, Name: ""}
	TEST_9156614022853705708                       = Chain{ChainID: "", Selector: 9156614022853705708, Name: ""}
	TEST_9248511054298050610                       = Chain{ChainID: "", Selector: 9248511054298050610, Name: ""}
	TEST_9264503539336248559                       = Chain{ChainID: "", Selector: 9264503539336248559, Name: ""}
	TEST_928756709184343973                        = Chain{ChainID: "", Selector: 928756709184343973, Name: ""}
	TEST_9574369650680012313                       = Chain{ChainID: "", Selector: 9574369650680012313, Name: ""}
	TEST_964127714438319834                        = Chain{ChainID: "", Selector: 964127714438319834, Name: ""}
	TEST_9675086780529785020                       = Chain{ChainID: "", Selector: 9675086780529785020, Name: ""}
	TEST_973671184102733124                        = Chain{ChainID: "", Selector: 973671184102733124, Name: ""}
	TEST_9932483170498916221                       = Chain{ChainID: "", Selector: 9932483170498916221, Name: ""}
	VELAS_MAINNET                                  = Chain{ChainID: "106", Selector: 374210358663784372, Name: "velas-mainnet"}
	VELAS_TESTNET                                  = Chain{ChainID: "111", Selector: 572210378683744374, Name: "velas-testnet"}
	WEMIX_MAINNET                                  = Chain{ChainID: "1111", Selector: 5142893604156789321, Name: "wemix-mainnet"}
	WEMIX_TESTNET                                  = Chain{ChainID: "1112", Selector: 9284632837123596123, Name: "wemix-testnet"}
	ZKLINK_NOVA_MAINNET                            = Chain{ChainID: "810180", Selector: 4350319965322101699, Name: "zklink_nova-mainnet"}
	ZKLINK_NOVA_TESTNET                            = Chain{ChainID: "810181", Selector: 5837261596322416298, Name: "zklink_nova-testnet"}
)

var ALL = []Chain{
	AREON_MAINNET,
	AREON_TESTNET,
	AVALANCHE_MAINNET,
	AVALANCHE_SUBNET_DEXALOT_MAINNET,
	AVALANCHE_SUBNET_DEXALOT_TESTNET,
	AVALANCHE_TESTNET_FUJI,
	AVALANCHE_TESTNET_NEXON,
	BERACHAIN_TESTNET_ARTIO,
	BERACHAIN_TESTNET_BARTIO,
	BINANCE_SMART_CHAIN_MAINNET,
	BINANCE_SMART_CHAIN_MAINNET_OPBNB_1,
	BINANCE_SMART_CHAIN_TESTNET,
	BINANCE_SMART_CHAIN_TESTNET_OPBNB_1,
	BITCICHAIN_MAINNET,
	BITCICHAIN_TESTNET,
	BITCOIN_MAINNET_BITLAYER_1,
	BITCOIN_MAINNET_BOB_1,
	BITCOIN_MAINNET_BOTANIX,
	BITCOIN_MAINNET_BSQUARED_1,
	BITCOIN_MERLIN_MAINNET,
	BITCOIN_TESTNET_BITLAYER_1,
	BITCOIN_TESTNET_BOTANIX,
	BITCOIN_TESTNET_BSQUARED_1,
	BITCOIN_TESTNET_MERLIN,
	BITCOIN_TESTNET_ROOTSTOCK,
	BITCOIN_TESTNET_SEPOLIA_BOB_1,
	BITTORRENT_CHAIN_MAINNET,
	BITTORRENT_CHAIN_TESTNET,
	CELO_MAINNET,
	CELO_TESTNET_ALFAJORES,
	COINEX_SMART_CHAIN_MAINNET,
	COINEX_SMART_CHAIN_TESTNET,
	CRONOS_MAINNET,
	CRONOS_TESTNET,
	CRONOS_TESTNET_ZKEVM_1,
	ETHEREUM_MAINNET,
	ETHEREUM_MAINNET_ARBITRUM_1,
	ETHEREUM_MAINNET_ARBITRUM_1_L3X_1,
	ETHEREUM_MAINNET_ARBITRUM_1_TREASURE_1,
	ETHEREUM_MAINNET_ASTAR_ZKEVM_1,
	ETHEREUM_MAINNET_BASE_1,
	ETHEREUM_MAINNET_BLAST_1,
	ETHEREUM_MAINNET_IMMUTABLE_ZKEVM_1,
	ETHEREUM_MAINNET_KROMA_1,
	ETHEREUM_MAINNET_LINEA_1,
	ETHEREUM_MAINNET_MANTLE_1,
	ETHEREUM_MAINNET_METIS_1,
	ETHEREUM_MAINNET_MODE_1,
	ETHEREUM_MAINNET_OPTIMISM_1,
	ETHEREUM_MAINNET_POLYGON_ZKEVM_1,
	ETHEREUM_MAINNET_SCROLL_1,
	ETHEREUM_MAINNET_TAIKO_1,
	ETHEREUM_MAINNET_WORLDCHAIN_1,
	ETHEREUM_MAINNET_XLAYER_1,
	ETHEREUM_MAINNET_ZKSYNC_1,
	ETHEREUM_TESTNET_GOERLI_ARBITRUM_1,
	ETHEREUM_TESTNET_GOERLI_BASE_1,
	ETHEREUM_TESTNET_GOERLI_LINEA_1,
	ETHEREUM_TESTNET_GOERLI_MANTLE_1,
	ETHEREUM_TESTNET_GOERLI_OPTIMISM_1,
	ETHEREUM_TESTNET_GOERLI_POLYGON_ZKEVM_1,
	ETHEREUM_TESTNET_GOERLI_ZKSYNC_1,
	ETHEREUM_TESTNET_HOLESKY,
	ETHEREUM_TESTNET_HOLESKY_FRAXTAL_1,
	ETHEREUM_TESTNET_HOLESKY_MORPH_1,
	ETHEREUM_TESTNET_HOLESKY_TAIKO_1,
	ETHEREUM_TESTNET_SEPOLIA,
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1,
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1_L3X_1,
	ETHEREUM_TESTNET_SEPOLIA_ARBITRUM_1_TREASURE_1,
	ETHEREUM_TESTNET_SEPOLIA_BASE_1,
	ETHEREUM_TESTNET_SEPOLIA_BLAST_1,
	ETHEREUM_TESTNET_SEPOLIA_CORN_1,
	ETHEREUM_TESTNET_SEPOLIA_IMMUTABLE_ZKEVM_1,
	ETHEREUM_TESTNET_SEPOLIA_KROMA_1,
	ETHEREUM_TESTNET_SEPOLIA_LENS_1,
	ETHEREUM_TESTNET_SEPOLIA_LINEA_1,
	ETHEREUM_TESTNET_SEPOLIA_LISK_1,
	ETHEREUM_TESTNET_SEPOLIA_MANTLE_1,
	ETHEREUM_TESTNET_SEPOLIA_METIS_1,
	ETHEREUM_TESTNET_SEPOLIA_MODE_1,
	ETHEREUM_TESTNET_SEPOLIA_OPTIMISM_1,
	ETHEREUM_TESTNET_SEPOLIA_POLYGON_VALIDIUM_1,
	ETHEREUM_TESTNET_SEPOLIA_POLYGON_ZKEVM_1,
	ETHEREUM_TESTNET_SEPOLIA_SCROLL_1,
	ETHEREUM_TESTNET_SEPOLIA_SONEIUM_1,
	ETHEREUM_TESTNET_SEPOLIA_UNICHAIN_1,
	ETHEREUM_TESTNET_SEPOLIA_WORLDCHAIN_1,
	ETHEREUM_TESTNET_SEPOLIA_XLAYER_1,
	ETHEREUM_TESTNET_SEPOLIA_ZIRCUIT_1,
	ETHEREUM_TESTNET_SEPOLIA_ZKSYNC_1,
	FANTOM_MAINNET,
	FANTOM_TESTNET,
	FILECOIN_MAINNET,
	FILECOIN_TESTNET,
	FRAXTAL_MAINNET,
	GETH_DEVNET_2,
	GETH_DEVNET_3,
	GETH_TESTNET,
	GNOSIS_CHAIN_MAINNET,
	GNOSIS_CHAIN_TESTNET_CHIADO,
	HEDERA_MAINNET,
	HEDERA_TESTNET,
	HYPERLIQUID_TESTNET,
	KAVA_MAINNET,
	KAVA_TESTNET,
	KUSAMA_MAINNET_MOONRIVER,
	NEAR_MAINNET,
	NEAR_TESTNET,
	NEONLINK_MAINNET,
	NEONLINK_TESTNET,
	PLUME_TESTNET,
	PLUME_TESTNET,
	POLKADOT_MAINNET_ASTAR,
	POLKADOT_MAINNET_CENTRIFUGE,
	POLKADOT_MAINNET_DARWINIA,
	POLKADOT_MAINNET_MOONBEAM,
	POLKADOT_TESTNET_ASTAR_SHIBUYA,
	POLKADOT_TESTNET_CENTRIFUGE_ALTAIR,
	POLKADOT_TESTNET_DARWINIA_PANGORO,
	POLKADOT_TESTNET_MOONBEAM_MOONBASE,
	POLYGON_MAINNET,
	POLYGON_TESTNET_AMOY,
	POLYGON_TESTNET_MUMBAI,
	PRIVATE_TESTNET_MICA,
	PRIVATE_TESTNET_OPALA,
	RONIN_MAINNET,
	RONIN_TESTNET_SAIGON,
	SEI_MAINNET,
	SEI_TESTNET_ATLANTIC,
	SOLANA_DEVNET,
	SOLANA_MAINNET,
	SOLANA_TESTNET,
	SONIC_TESTNET,
	STORY_TESTNET,
	TELOS_EVM_MAINNET,
	TELOS_EVM_TESTNET,
	TEST_10089241509396411113,
	TEST_10106333385848939617,
	TEST_10497629267361915835,
	TEST_10537986502862404866,
	TEST_10547673735879567911,
	TEST_11335955773964346155,
	TEST_11754399446572002459,
	TEST_11787463284727550157,
	TEST_11985232338641871056,
	TEST_12027427861168955422,
	TEST_12226902941055802385,
	TEST_12470167056735102403,
	TEST_12499149790922928210,
	TEST_12513826466599144030,
	TEST_1273605685587320666,
	TEST_12965905455277595820,
	TEST_13087962012083037329,
	TEST_13443138560923813712,
	TEST_13648736134397881410,
	TEST_13781595843667691007,
	TEST_13819071330241498802,
	TEST_13936493323944617843,
	TEST_13973515790491921010,
	TEST_14506622911400094011,
	TEST_1488785539820432596,
	TEST_14943531413383612703,
	TEST_15168140751097121912,
	TEST_15210860601736105873,
	TEST_15447447865219782832,
	TEST_15733873364998401606,
	TEST_15767478222558315144,
	TEST_15804983202763665802,
	TEST_15896959195233368219,
	TEST_15945074456050759193,
	TEST_15998314635132476942,
	TEST_16449698933146693970,
	TEST_16591966440843528322,
	TEST_16702426279731183946,
	TEST_17198166215261833993,
	TEST_17251043223284625647,
	TEST_17514102371649734225,
	TEST_17580537314894454709,
	TEST_176199025415897437,
	TEST_17759418850483131633,
	TEST_17810359353458878177,
	TEST_18316006852148771137,
	TEST_1974710175227680991,
	TEST_2509173735760116798,
	TEST_2783890746839497525,
	TEST_2953028829530698683,
	TEST_328334718812072308,
	TEST_3330151784927722907,
	TEST_3574539439524578558,
	TEST_3632230855428784129,
	TEST_3740583887329090549,
	TEST_4066443121807923198,
	TEST_4174149892778961910,
	TEST_4543928599863227519,
	TEST_4716670523656754658,
	TEST_5548718428018410741,
	TEST_5614341928911841614,
	TEST_5721565186521185178,
	TEST_6059917085984771915,
	TEST_6443235356619661032,
	TEST_6448403805635971860,
	TEST_665284410079532457,
	TEST_6676710761873615962,
	TEST_6690738652320128159,
	TEST_6742472197519042017,
	TEST_6747736380229414777,
	TEST_6751512843227450641,
	TEST_6875898693582952601,
	TEST_7005880874640146484,
	TEST_7032045258883126022,
	TEST_7353384334508842175,
	TEST_7404045285477377670,
	TEST_7431973150957944526,
	TEST_7585715102059681757,
	TEST_7715160997071429212,
	TEST_7777066535355430289,
	TEST_781901677223027175,
	TEST_7823363553221722351,
	TEST_789068866484373046,
	TEST_7961714422080771198,
	TEST_8015762103567576333,
	TEST_8211981504472319767,
	TEST_8354317460459584308,
	TEST_8412806778050735057,
	TEST_8694984074292254623,
	TEST_8698844633699288298,
	TEST_8794884152664322911,
	TEST_8966794841936584464,
	TEST_909606746561742123,
	TEST_9156614022853705708,
	TEST_9248511054298050610,
	TEST_9264503539336248559,
	TEST_928756709184343973,
	TEST_9574369650680012313,
	TEST_964127714438319834,
	TEST_9675086780529785020,
	TEST_973671184102733124,
	TEST_9932483170498916221,
	VELAS_MAINNET,
	VELAS_TESTNET,
	WEMIX_MAINNET,
	WEMIX_TESTNET,
	ZKLINK_NOVA_MAINNET,
	ZKLINK_NOVA_TESTNET,
}
