// Code generated by go generate please DO NOT EDIT
package chain_selectors

type BitcoinChain struct {
	ChainID  string
	Selector uint64
	Name     string
	VarName  string
}

var (
	BITCOIN_MAINNET = BitcoinChain{ChainID: "bitcoin_mainnet", Selector: 5295418179606748534, Name: "bitcoin-mainnet"}
	BITCOIN_TESTNET = BitcoinChain{ChainID: "bitcoin_testnet", Selector: 8997884582513251897, Name: "bitcoin-testnet"}
)

var BitcoinALL = []BitcoinChain{
	BITCOIN_MAINNET,
	BITCOIN_TESTNET,
}
