name: Go - Build and test

on: [ push ]

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: false
      - name: Build
        run: go build -v ./...
      - name: Make sure generated files are updated
        run: |
          if go generate | grep -q 'no changes detected'; then
            exit 0;
          fi
          exit 1;
      - name: Test
        env:
          EXTRA_SELECTORS_FILE: ./test_extra_selectors.yml
        run: go test -v ./...
